### ISSUE TITLE
build hangs when project is not under git control

### ISSUE THREAD

**Issue by haiko** [spotify/docker-maven-plugin#102]
using version 0.2.11 my docker:build goal freezes. After debugging  I discovered that line 216 in BuildMojo.class was the cullprit :
    final String commitId = git.isRepository() ? git.getCommitId() : null; 

After adding my project to Git the build ran fine.
OS is Ubuntu 14.04

**Comment by davidxia** [comment]
@haiko thanks for the bug report. Can you give more details on how it froze? If your project wasn't a git repo, shouldn't `commitId` have simply been `null`? Were you using `${gitShortCommitId}` anywhere in your pom.xml?

**Comment by mattnworb** [comment]
To figure out if the project is under git control, jgit will walk from the current directory to it's parent directory and so on checking for a `.git` directory until there are no more parent directories.

This is triggered when the `com.spotify.docker.Git` class [is instantiated in the line before](https://github.com/spotify/docker-maven-plugin/blob/cbac254bcaa1c1dcf9a638575ca6a14d5a4c953f/src/main/java/com/spotify/docker/BuildMojo.java#L253) the one that @haiko points out.

In theory this shouldn't take very long (unless the working directory is incredibly nested, or if there is some platform where `File.getParentFile()` can never return `null`), or if access to the filesystem of the path is incredibly slow (perhaps NFS mounts?). 

@haiko if you are still experiencing this problem at all, it looks like jgit will [curtail it's directory-traversal at a certain point if the `GIT_CEILING_DIRECTORIES `](https://github.com/eclipse/jgit/blob/11a0dffd16e998959e3145de9c48dbdaf8f9757b/org.eclipse.jgit/src/org/eclipse/jgit/lib/BaseRepositoryBuilder.java#L408) environment variable [is set](https://github.com/eclipse/jgit/blob/11a0dffd16e998959e3145de9c48dbdaf8f9757b/org.eclipse.jgit/src/org/eclipse/jgit/lib/BaseRepositoryBuilder.java#L501). This might be helpful in short-circuiting the path-walking.
