### ISSUE TITLE
Private Repo Authentication: use auth token from ~/.dockercfg 

### ISSUE THREAD

**Issue by olkulyk** [spotify/docker-maven-plugin#104]
Is it be possible to use auth token from ~/.dockercfg (or ~/.docker/config.json) instead of using plain username/password authentication?

https://github.com/docker/docker/pull/12009

**Comment by davidxia** [comment]
@olkulyk It's certainly possible. What's the use case or problem you're looking to solve?

**Comment by tonyshearer** [comment]
+1
This is necessary to allow access to Google Container Registry:

gcloud docker -a  
mvn docker:push

The first command updates the .dockercfg with temporary access tokens for *.gcr.io. Currently these are not picked up by the docker-maven-plugin, so there is an auth error when accessing the registry.

**Comment by j3rmwarfare** [comment]
+1
my group is using Artifactory as our local docker repository with a service account that only a certain number of users should have access to.  Requiring the info in the settings.xml exposes this information unnecessarily.

In addition, I can't get the authentication to work with the edits to settings.xml, fails with "{\"error\": \"Unauthorized getting repository images\"}".

**Comment by davidxia** [comment]
We're definitely open to PRs on this :)

**Comment by ravwojdyla** [comment]
+1

**Comment by buzzo** [comment]
+1

**Comment by starlight36** [comment]
+1

**Comment by mattnworb** [comment]
https://github.com/spotify/docker-client/pull/219 should help provide this.

**Comment by davidxia** [comment]
This should be addressed by https://github.com/spotify/docker-client/pull/268. I'll close this for now. We can reopen if there are more issues.
