### ISSUE TITLE
Parallel build compatibility

### ISSUE THREAD

**Issue by yaronr** [spotify/docker-maven-plugin#106]
Hi.

During parallel builds, I get:
docker-maven-plugin:0.2.11:build (default) on project x: Exception caught: java.net.SocketException: Socket closed 

mvn -T 1C package

**Comment by davidxia** [comment]
@yaronr Do you have more details? I ran `mvn -T 1C package docker:build` on a project and it succeeded. I'm on mac boot2docker 1.6.2.

**Comment by docbobo** [comment]
Please checkout https://github.com/docbobo/ParallelDockerMavenTest and run `mvn -T 1C package`. For me, this produces 

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.2:build (build-docker-image) on project ImageB: Exception caught: java.net.SocketException: Socket closed -> [Help 1]
```

**Comment by mattnworb** [comment]
Sounds related to #114.

**Comment by mattnworb** [comment]
#115 also.

**Comment by davidxia** [comment]
should be fixed by https://github.com/spotify/docker-maven-plugin/pull/383
