### ISSUE TITLE
Authentication Error When Pushing to Private Repo

### ISSUE THREAD

**Issue by amracel** [spotify/docker-maven-plugin#111]
I'm trying to push my container to my private registry.I've added the URL and server ID to the pom file:

    <serverId>private-docker</serverId>
    <registryUrl>http://[private ip]:5000/v2/</registryUrl>

Then I added my username and password to my settings.xml file, as suggested. With this setup, I receive the following error:

    [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.11:build (default-cli) on project jfinsys-vandelay: Exception caught: Incomplete Docker registry authorization credentials. Please provide all of username, password, and email or none. -> [Help 1]

If I add my email to the settings.xml file, I get an error, too, since email is not an acceptable tag for server:

    Unrecognised tag: 'email' (position: START_TAG seen ...</password>\n    <email>... @10:12) 

If I remove the username/pw altogether, the error is that Authentication is required:

    [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.11:build (default-cli) on project jfinsys-vandelay: Exception caught: Error pushing to registry: Authentication is required. -> [Help 1]

This is all a test setup now, to try to figure out how it works. So authentication is *not* required on the server. It will actually just look to see that authentication is included in the header, but not care what is in there.

**Comment by davidxia** [comment]
@amracel Sorry for the bad docs. We've updated the [auth section of the README][1]. Email should be wrapped in a configuration element. Does this solve it for you?

```
<servers>
  <server>
    <id>docker-hub</id>
    <username>foo</username>
    <password>secret-password</password>
    <configuration>
      <email>foo@foo.bar</email>
    </configuration>
  </server>
</servers>
```

  [1]: https://github.com/spotify/docker-maven-plugin#authenticating-with-private-registries

**Comment by davidxia** [comment]
I'm going to close for now. Reopen if you have questions.

**Comment by herau** [comment]
@davidxia i have the same issue (with 0.3.6 version). 
Does the email configuration is mandatory in the `settings.xml` file ?
