### ISSUE TITLE
How does one access the git hash in docker:remove

### ISSUE THREAD

**Issue by deardooley** [spotify/docker-maven-plugin#112]
I'd like to attach the docker:remove goal to my project's clean phase with a conditional flag so I can optionally reset the entire environment. Currently we build a container using the artifact id as the short name and tag it with `latest`, `${project.version}`, and the git hash using your plugin's `useGitCommitId` flag. Is there a way to reference the git short commit id that was used in the build from within the remove goal?

**Comment by davidxia** [comment]
Hm, is there a way that `RemoveImageMojo` can tell which git commit ID was used in the prior execution of `BuildMojo`?
