### ISSUE TITLE
Empty CMD output

### ISSUE THREAD

**Issue by mattbroekhuis** [spotify/docker-maven-plugin#118]
if I do not specify a command, the resulting docker file looks like this. I would expect it to not include the CMD if i do not specify one. I want to just inherit the parent image's CMD, which is how it works if you omit the statement. What do you suggest?

````
FROM btf/jetty
CMD []
ADD /var/lib/jetty/webapps/api.war /var/lib/jetty/webapps/api.war
````

**Comment by davidxia** [comment]
Yea that's a bug. It should omit the `CMD` altogether instead of outputing an empty list.

**Comment by nbleisch** [comment]
Yeah, I've the same problem here and just wanted to create an issue for that.
Luckily I found this one. I'm quite new to the mechanics of Docker, so I wasn't sure if intended or not. 

Just wanted to inherit from "tomcat:8.0.20-jre8" as base image which has "["catalina.sh", "run"]" definied in its CMD-Scope. 

However. Awesome work guys. Rly appreciate it.
