### ISSUE TITLE
ADD command incorrect for tar.gz files

### ISSUE THREAD

**Issue by aburnett** [spotify/docker-maven-plugin#123]
Adding a tar.gz file creates an ADD command which causes an extra directory to be created with the same name as the tar.gz in the target path. The expected behavior is that the archive would be extracted in the target path.

    <resource>
        <directory>${project.build.directory}</directory>
        <include>${project.artifactId}.tar.gz</include>
        <targetPath>/opt/apps/</targetPath>
    </resource>

Creates the following command during build

    ADD /opt/apps/spar-api.tar.gz /opt/apps/spar-api.tar.gz

Which results in `/opt/apps/spar-api.tar.gz/<contents of archive>` where it should be `/opt/apps/<contents of archive>`

**Comment by davidxia** [comment]
@aburnett So the Dockerfile command should be `ADD /opt/apps/spar-api.tar.gz /opt/apps/`?

**Comment by chris-snider** [comment]
Hi,

According to the docker docs, an ADD is supposed to copy and unpack if in a recognized format.  If you want to have a copy of the tar.gz in the resulting image, a copy command should be used.

REF: https://docs.docker.com/reference/builder/#add
•  If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed. When a directory is copied or unpacked, it has the same behavior as tar -x: the result is the union of:

  1.  Whatever existed at the destination path and
  2.  The contents of the source tree, with conflicts resolved in favor of “2.” on a file-by-file basis.



REF: http://stackoverflow.com/questions/24958140/docker-copy-vs-add

You should check the ADD<http://docs.docker.com/reference/builder/#add> and COPY<http://docs.docker.com/reference/builder/#copy> documentations for an exhaustive description of their behaviours, but in a nutshell the major difference is that ADD can do more than COPY:

  *   ADD allows <src> to be an URL
  *   If the <src> parameter of ADD is an archive in a recognised compression format, it will be unpacked


Chris Snider
Senior Software Engineer
Intelligent Software Solutions, Inc.
[Description: Description: Description: cid:image001.png@01CA1F1F.CBC93990]

**Comment by davidxia** [comment]
Yea I saw that. I think we all agree that ADD *unpacks* tar archives. The question is whether this plugin should be smart about tar files and instead of naively writing `ADD /opt/apps/spar-api.tar.gz /opt/apps/spar-api.tar.gz` write `ADD /opt/apps/spar-api.tar.gz /opt/apps/` instead.

**Comment by aburnett** [comment]
@chris-snider that's correct about copy/add. I'm going for copy+unpack so ADD is correct.

@davidxia ya, that's what I think the command should be. Perhaps the easiest solution is to just pass `targetPath` verbatim as the last argument to `ADD`. Then the behavior would match the [docs](https://docs.docker.com/reference/builder/#add) and you wouldn't have to get fancy in the plugin.
