### ISSUE TITLE
Be able to define working directory

### ISSUE THREAD

**Issue by davidkarlsen** [spotify/docker-maven-plugin#124]
It should be possible to define the current working directory when invoking the docker binary, so that triggers that expect files to be in certain places can be used.

```
Step 0 : FROM mybaseimage/jetty:latest
[91m# Executing 2 build triggers

Trigger 0, COPY build.properties /tmp/build.properties
Step 0 : COPY build.properties /tmp/build.properties
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by davidxia** [comment]
Yes, see
https://github.com/spotify/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/BuildMojo.java#L138.
Sorry, our docs are lacking and should be updated.

On Wed, Aug 12, 2015 at 5:01 AM, David J. M. Karlsen <
notifications@github.com> wrote:

> It should be possible to define the current working directory when
> invoking the docker binary, so that triggers that expect files to be in
> certain places can be used.
>
> Step 0 : FROM mybaseimage/jetty:latest
> [91m# Executing 2 build triggers
>
> Trigger 0, COPY build.properties /tmp/build.properties
> Step 0 : COPY build.properties /tmp/build.properties
> [INFO] ------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-maven-plugin/issues/124>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com
