### ISSUE TITLE
DOCKER Build Failure

### ISSUE THREAD

**Issue by gireeshbabum** [spotify/docker-maven-plugin#129]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Copying /home/tcstarget/target/myproject-0.0.1-SNAPSHOT.jar -> /home/tcstarget/target/docker/myproject-0.0.1-SNAPSHOT.jar
[INFO] No resources will be copied, no files match specified patterns
[INFO] Building image dockertest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:00.259s
[INFO] Finished at: Thu Aug 27 15:28:15 CDT 2015
[INFO] Final Memory: 27M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.3:build (default-cli) on project myproject: Exception caught: Request error: POST unix://localhost:80/v1.12/build?t=dockertest: 500: HTTP 500 Internal Server Error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mattnworb** [comment]
@gireeshbabum if you are still having issues, can you please provide more information such as what the configuration of the plugin looks like? There is not really any info here to troubleshoot.

**Comment by kcheng-mvp** [comment]
<plugins>
                    <plugin>
                        <groupId>com.spotify</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>0.3.5</version>
                        <configuration>
                            <imageName>${project.artifactId}:${project.version}</imageName>
                            <dockerDirectory>${project.build.directory}</dockerDirectory>
                            <resources>
                                <resource>
                                    <targetPath>/</targetPath>
                                    <directory>${basedir}/target/bin</directory>
                                    <include>${project.artifactId}-fabric-${project.version}-bin.zip</include>
                                </resource>
                            </resources>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>install</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>

--- I ran into the same issue

**Comment by mattnworb** [comment]
If docker-maven-plugin is reporting that the daemon returned a 500 Internal Server Error, check the daemon's log for more info: https://github.com/spotify/docker-maven-plugin#internalservererrorexception-http-500-internal-server-error
