### ISSUE TITLE
Suppress display of progress bars in maven batch mode (-B)

### ISSUE THREAD

**Issue by avallen** [spotify/docker-maven-plugin#130]
Invoking maven in non-interactive batch mode (--batch-mode / -B) should suppress the display of progress bars when pushing, just like for the maven-deploy-plugin plugin e.g.

**Comment by qoomon** [comment]
+1

**Comment by qoomon** [comment]
Im still thinking this is important to have a clean build log in ci/cd systems

**Comment by mbendaniel-n** [comment]
+1
