### ISSUE TITLE
get docker image failed behind a http proxy

### ISSUE THREAD

**Issue by tranchida** [spotify/docker-maven-plugin#135]

**Comment by FugDev** [comment]
do you have this error too?
org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection

**Comment by FugDev** [comment]
set DOCKER_HOST=tcp://<YOUR_IP>:2376 on cmd line before executing mvn or set environment variable in runconfig of eclipse/sts

**Comment by tranchida** [comment]
Thank you, I have to try.

**Comment by mattnworb** [comment]
@tranchida is this still an issue? Can you list steps to reproduce?
