### ISSUE TITLE
Mac OS 10.10: does not work with Docker Toolbox 1.8.1.c

### ISSUE THREAD

**Issue by EvgeniGordeev** [spotify/docker-maven-plugin#136]
mvn docker:build results in error 'Exception caught: java.nio.file.NoSuchFileException: /Users/<user>/.boot2docker/certs/boot2docker-vm/ca.pem'. Tested on 0.3.3 build.

**Comment by mattnworb** [comment]
Sorry for the late reply @EvgeniGordeev but are you still having this issue? What does the `DOCKER_CERT_PATH` environment variable look like?

**Comment by EvgeniGordeev** [comment]
@mattnworb Tested on latest 1.9.0d docker-toolbox and it works successfully. 

I identified two issues that are related to docker toolbox that seem to be helpful or even useful to add to README:
1) after uninstalling boot2docker remove DOCKER_ variables from ~/.bash_profile
2) execute eval "$(docker-machine env default)" before working with the docker plugin
