### ISSUE TITLE
[Question] Pushing To A Private Registry: Am I Missing Something?

### ISSUE THREAD

**Issue by LTheobald** [spotify/docker-maven-plugin#137]
Hi all,

I'm trying to push to a private registry but not having much luck.  The registry is running unsecured for now (while I get going).  My `pom.xml` contains the following (mainly cobbled together from the docs)

    <plugin>
      <groupId>com.spotify</groupId>
      <artifactId>docker-maven-plugin</artifactId>
      <version>0.3.3</version>
      <configuration>
        <imageName>customer-service</imageName>
        <baseImage>java</baseImage>
        <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
        <serverId>office-dockerregistry</serverId>
        <registryUrl>http://office-dockerregistry.openobjects.com:5000/v2/</registryUrl>
        
        <resources>
          <resource>
            <directory>${project.build.directory}</directory>
            <include>${project.build.finalName}.jar</include>
          </resource>
        </resources>
      </configuration>
      <executions>
        <execution>
          <phase>package</phase>
          <goals>
            <goal>build</goal>
          </goals>
        </execution>
      </executions>
    </plugin>

In my `settings.xml` I have

    <server>
      <id>office-dockerregistry</id>
      <username>lee</username>
      <password>password</password>
      <configuration>
        <email>lee@openobjects.com</email>
      </configuration>
    </server>

But when I call `mvn docker:push`, I get an error message containing:

    [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.3:push (default-cli) on project customer-service-core: Exception caught: Post https://registry-1.docker.io/v2/library/customer-service/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=lee&scope=repository%3Alibrary%2Fcustomer-service%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized -> [Help 1]

So it looks like the `registryUrl` isn't being picked up. Can anyone see anything obvious I'm missing?

**Comment by chovatiyabhaevesh** [comment]
There is a bug in plugin. Issue is that  imageName include tag.

<imageName>server:port/customer-service:projectversion</imageName>

And its work for me.

**Comment by nilsga** [comment]
I'm hitting this issue as well. No matter what I set as `registryUrl`, it's trying to push to docker.io. Will this be addressed anytime soon?

**Comment by efontana** [comment]
I had this same issue, I got around it by making sure that the serverId matched the settings.xml server id

**Comment by ricard2k** [comment]
I'd same problem. trying to push to dockerIo without take care of registryUrl

**Comment by davidxia** [comment]
You need to prepend your image tag with the url to your registry. e.g if I want to push myimage:0.1.0 to myregistry.com, I need to tag the image myregistry.com/myimage:0.1.0 and then push that.

**Comment by LTheobald** [comment]
Hi all. Sorry for the late reply. Just a quick thanks for clarifying this for me :+1:
