### ISSUE TITLE
resource not copied

### ISSUE THREAD

**Issue by nmarasoiu** [spotify/docker-maven-plugin#145]
Hi,

The docker is being built but it does not contain the war file in /.
Please advise,

```
<plugin>
    <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.3.5</version>
                <configuration>
                    <imageName>adswizz/${project.artifactId}:${project.version}</imageName><!--:${build.timestamp}-->
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>aas-api-2.16.11-${build.timestamp}.war</include>
                            <!--<include>${project.artifactId}-2.16.11-${build.timestamp}.war</include>-->
                            <!--<include>${project.artifactId}-${project.version}-${build.timestamp}.war</include>-->
                            <!--<include>${project.build.finalName}.war</include>-->
                        </resource>
                    </resources>
                </configuration>
            </plugin>
```

**Comment by mattnworb** [comment]
Sounds like same issue as #146.

**Comment by dawidmalina** [comment]
What I can say. My original PR that can be checked here https://github.com/oberthur/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/BuildMojo.java works. During PR review maintainers has decided to propose many optimizations to my code and one of this broke this functionality.

**Comment by mattnworb** [comment]
@nmarasoiu are you still having the issue with version 0.3.7 of the plugin? Can you include the log output from the plugin as well?

If you specify a `<dockerDirectory>`, the plugin uses the Dockerfile in that directory and copies the `<resources>` in preparation for whatever instructions the Dockerfile contains. What does your Dockerfile look like?

**Comment by hlavacek** [comment]
I've hit the same issue with 0.4.13 version of the plugin, what happens for me is that the plugin uses the <resources> content and copies the resources to target/docker folder - but nothing adds them to the image.

What was required was to add a COPY instruction into the custom Dockerfile to copy from the target/docker folder (with relative path starting on that folder) to the image.

The documentation for the plugin doesn't mention this in any way, can we enhance at least the documentation?

**Comment by davidxia** [comment]
I think #157 fixes this. Please comment here if it doesn't work with the latest version.
