### ISSUE TITLE
Push To Docker Hub

### ISSUE THREAD

**Issue by jdhankins** [spotify/docker-maven-plugin#147]
I'm looking for instructions or an example of how to push to a private repository on Docker Hub.

We are executing the plugin as part of our CI process in Jenkins, so ideally, would like to be able to run mvn clean build -DpushImage.

I'm just unclear on what parameters/urls are required.

Thanks for any help with this.

jdh

**Comment by sloppycoder** [comment]
I have the same problem. error message when running maven -X..

```
...l evel=error msg="HTTP Error" err="Error: Status 403 trying to push repository sloppycoder/infra-auth-server to official registry: needs to be forced" statusCode=403
```

so how to I specify force?

I'm running on Centos7.1. 
Docker version 1.8.2, build bb472f0/1.8.2

**Comment by officialpatterson** [comment]
In the readme file there is a section on authenticating with private registries, have you tried this?

**Comment by mattnworb** [comment]
As @officialpatterson mentioned this is documented [in the README](https://github.com/spotify/docker-maven-plugin#authenticating-with-private-registries) - @jdhankins or @sloppycoder please let us know if the setup documented there does not work for you and if not, please tell us what the pom.xml looks like.

**Comment by marcolenzo** [comment]
@mattnworb I do have the same problem of @sloppycoder when pushing to Docker Hub. 

` Error: Status 403 trying to push repository marcolenzo/checkip to official registry: needs to be forced`.

I am successful from command line (i.e. `docker push`) which in fact include the force flag in the request while the plugin doesn't.

`POST /v1.20/images/marcolenzo/checkip/push?force=1&tag=0.0.1-SNAPSHOT`

vs

`POST /v1.20/images/marcolenzo/checkip/push?&tag=0.0.1-SNAPSHOT`

I included the server in my maven `settings.xml` looks and my POM looks like this:

```
<plugin>
	<groupId>com.spotify</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>0.4.5</version>
	<configuration>
		<imageName>marcolenzo/checkip:${project.version}</imageName>
		<dockerDirectory>${basedir}/src/main/docker</dockerDirectory>
		<serverId>docker-hub</serverId>
		<resources>
			<resource>
				<targetPath>/</targetPath>
				<directory>${project.build.directory}</directory>
				<include>${project.build.finalName}.jar</include>
			</resource>
		</resources>
	</configuration>
</plugin>
```

Any idea on what am I doing wrong?
