### ISSUE TITLE
Setting up DOCKER_HOST for Private push

### ISSUE THREAD

**Issue by vishalvsh1** [spotify/docker-maven-plugin#162]
Hi, 
  As per documentation 
To push the image you just built to the registry, specify the pushImage flag.

mvn clean package docker:build -DpushImage

By default the plugin will try to connect to docker on localhost:2375. Set the DOCKER_HOST environment variable to connect elsewhere.

DOCKER_HOST=tcp://<host>:2375

Now, I feel there is some glitch here, If i setup this I get following error.

[INFO] Building image someting:0.0.9-SNAPSHOT
Dec 04, 2015 9:02:57 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://artifactory.something.com:5002: Broken pipe
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] something ........................................ SUCCESS [  3.478 s]
[INFO] server ............................................. FAILURE [ 47.277 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min (Wall Clock)
[INFO] Finished at: 2015-12-04T09:02:57+00:00
[INFO] Final Memory: 82M/1373M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.1.1:build (default) on project server: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException: Cannot retry request with a non-repeatable request entity: Broken pipe -> [Help 1]
[ERROR] 

This means its trying to pull images from my private registry and not able to find it.

If i do not setup this, my build failed to push as it can not push to docker hub registry.

How can i define different registry for pull and push of my images?

**Comment by mattnworb** [comment]
@vishalvsh1 can you try using a more recent version of the plugin? `0.1.1` is nearly one year old. Please try `0.3.8`.

If you are still having issues, can you paste the output when you run your maven command with the `-e` and `-X` flags?

**Comment by vishalvsh1** [comment]
Thanks, 0.3.7 worked fine for me.
