### ISSUE TITLE
Release perform is not pusing images

### ISSUE THREAD

**Issue by vishalvsh1** [spotify/docker-maven-plugin#166]
We have all configuration set for the build and push to private registry, -DpushImage is pushing the docker images when run with normal build.
Like below

    clean deploy -U -DpushImage

BUT
If we try using Release commands.

    mvn release:prepare release:perform -U -DpushImage

Above is not pushing the image, Do i have to setup anything?

**Comment by mattnworb** [comment]
IIRC the maven-release-plugin runs the separate steps in forked builds, so your `-DpushImage` argument doesn't make it to the JVM running those maven commands. I think you can configure http://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html#arguments to have `-DpushImage`.

You might want to also look at having the docker image just built in `perform` and not `prepare`

**Comment by brianshowers** [comment]
You might also consider just changing the configuration of the release plugin to include the docker goals that you want executed.  For example, I use the following on my project to make sure that the image is built during release preparation (to test the image build configuration) and then pushed to the repo during release perform (to mimic deploying the other artifacts):

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-release-plugin</artifactId>
    <version>2.5.2</version>
    <configuration>
        <!-- Modify the goals to include building and deploying the docker container -->
        <preparationGoals>clean verify docker:build</preparationGoals>
        <goals>deploy docker:build docker:push</goals>
    </configuration>
</plugin>
```

**Comment by cthiebault** [comment]
Here is my configuration to build, tag (short & long name) and push image during a Maven release. 

```
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <configuration>
    <imageName>my-image-short-name</imageName>
    <dockerDirectory>[...]</dockerDirectory>
    <forceTags>true</forceTags>
    <imageTags>
      <tag>${project.version}</tag>
    </imageTags>
    <serverId>my-docker-server</serverId>
    <registryUrl>docker.my-company.com</registryUrl>
    <resources>[...]</resources>
  </configuration>
  <executions>
    <execution>
      <id>build-image</id>
      <phase>package</phase>
      <goals>
        <goal>build</goal>
      </goals>
    </execution>
    <execution>
      <id>tag-image</id>
      <phase>package</phase>
      <goals>
        <goal>tag</goal>
      </goals>
      <configuration>
        <image>my-image-short-name:${project.version}</image>
        <newName>docker.my-company.com/my-image-short-name:${project.version}</newName>
      </configuration>
    </execution>
    <execution>
      <id>push-image</id>
      <phase>deploy</phase>
      <goals>
        <goal>push</goal>
      </goals>
      <configuration>
        <imageName>docker.my-company.com/my-image-short-name:${project.version}</imageName>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by kkorada** [comment]
how to build docker image while release:prepare release:perform.

my docker maven plugin is as follows
<plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.1</version>
                <configuration>
                    <imageName>XXXXXXXXXXX</imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.war</include>
                        </resource>
                    </resources>
                </configuration>
            </plugin>

**Comment by mattnworb** [comment]
closing as @cthiebault and @brianshowers comments both mention good ways to configure the plugin or release-plugin to accomplish this goal.
