### ISSUE TITLE
Please start a changelog.txt

### ISSUE THREAD

**Issue by yaronr** [spotify/docker-maven-plugin#167]
Hi
Great project.

It would be great if there would be a changelong

**Comment by davidxia** [comment]
We tag our commits with versions. Does `git log --decorate=full --pretty=oneline` help?

**Comment by yaronr** [comment]
That's assuming everyone has a git clone. I'm just using it through mvn.

**Comment by mattnworb** [comment]
It's also possible to use the releases page here on Github to document what is in each release. The nice aspect of that feature is that it recognizes the tags that are created at release time and creates something in the UI for each one. The only manual work to do is adding notes for each tag about what was in the git commits for those tags.  I think it would be worthwhile to have this.

**Comment by davidxia** [comment]
Yea we should do this.
