### ISSUE TITLE
What is the correct syntax to pass enviornment variable to docker image??

### ISSUE THREAD

**Issue by itshemant4u** [spotify/docker-maven-plugin#168]
I am using the following syntax to pass enviornment variable to docker image using spotify maven plugin

`<env> <Ver>3.4</Ver> </env> `

However, the above syntax is not working.

**Comment by mattnworb** [comment]
Can you post the complete plugin configuration that is giving you an issue?

See [this test](https://github.com/spotify/docker-maven-plugin/blob/master/src/test/resources/pom-build-generated-dockerfile.xml#L26) for an example that works.

**Comment by itshemant4u** [comment]
```
<build>
		<plugins>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.3.7</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<imageName>image1/${project.artifactId}</imageName>
					<imageTags>
						<imageTag>${project.version}</imageTag>
					</imageTags>
					<forceTags>true</forceTags>
					<dockerDirectory>${project.basedir}/src/main/docker</dockerDirectory>
          <resources>
            <resource>
          <env>
            <VER>${project.version}</VER>
          </env>
        </resource>
        </resources>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by mattnworb** [comment]
'env' is expected at the top local of the configuration block, not nested inside a resource.

**Comment by mattnworb** [comment]
Also note that if you specify a dockerDirectory then the plugin won't generate a Dockerfile for you (it expects to find one in that directory) so setting the 'env' would be moot anyway.

**Comment by itshemant4u** [comment]
I definitely need a Dockerfile within the dockerdirectory. Will 'env' work in that situation too?? 
It doesn't seem to be working for me with the following pom.xml
```
	<build>
		<plugins>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.3.7</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<imageName>image1/${project.artifactId}</imageName>
					<imageTags>
						<imageTag>${project.version}</imageTag>
					</imageTags>
					<forceTags>true</forceTags>
					<dockerDirectory>${project.basedir}/src/main/docker</dockerDirectory>
          <env>
            <VER>${project.version}</VER>
          </env>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by itshemant4u** [comment]
Do we have support for ARGS instruction with this plugin??

https://docs.docker.com/engine/reference/builder/#arg

**Comment by mattnworb** [comment]
If you have dockerDirectory set then all configuration properties like `env` `baseImage` `workDir` `cmd` `entryPoint` are ignored. You should put those `ENV` instructions in the Dockerfile.

No this plugin does not yet support ARGS and I'm not sure what that would look like to be honest,

**Comment by itshemant4u** [comment]
Hi Matt,

Thanks for your response !!
How about having the ARGS look like something as below:  
```
<docker-build-args>
     <docker-build-arg>my_arg=${maven.releaseVersion}</docker-build-arg>
<docker-build-args>
```

**Comment by mattnworb** [comment]
Closing this since the original question is resolved. Pull Requests to add ARGS support would be very welcome.
