### ISSUE TITLE
Including multiple workdir instructions

### ISSUE THREAD

**Issue by itshemant4u** [spotify/docker-maven-plugin#169]
What is the syntax to include multiple workdir instructions?

In other words, what is the pom.xml equivalent of the below dockerfile:

```
WORKDIR /tmp/dir1
RUN pwd
WORKDIR /tmp/dir2
RUN pwd
```

**Comment by mattnworb** [comment]
Multiple `WORKDIR`s is not currently supported if you are using the plugin to generate the Dockerfile. If you want to have multiple `WORKDIR`s then your best option is to use your own Dockerfile and point to it with the `dockerDirectory` configuration property.

**Comment by mattnworb** [comment]
The problem with multiple `WORKDIR`s when the plugin is generating the Dockerfile is that there would need to be a mechanism for you to tell the plugin which `WORKDIR` command to set before which other commands, and the proper sequence for outputting all the final commands, and simply using a regular Dockerfile is the simplest way of doing that.
