### ISSUE TITLE
[Documentation] Pushing private repo tagged image fails as it tries to push the original image 

### ISSUE THREAD

**Issue by mattreyuk** [spotify/docker-maven-plugin#171]
The docs for Using with private images say "Alternatively, if you wish to use a short name in docker:build you can use docker:tag to tag the just-built image with the full registry hostname." The problem is that when I then do `docker:push` it tries to push `my-image` rather than `registry.example.com/my-image` because `docker:push` uses the value of `imageName`. 

You need to do `docker:tag -DpushImage` to push your newly tagged image.

I'll create a pull request shortly to add this to the README and ref this issue.

**Comment by mattnworb** [comment]
Fixed by https://github.com/spotify/docker-maven-plugin/pull/172
