### ISSUE TITLE
Tag is not skipped when skiping build

### ISSUE THREAD

**Issue by miguelammatos** [spotify/docker-maven-plugin#174]
When setting the property skipDockerBuild to true the build execution is correctly skipped but the tag execution is not.

How to reproduce:
Using the example on the main page, set the property 
<skipDockerBuild>true</skipDockerBuild>
in the configuration section.

Sample output:

[INFO] --- docker-maven-plugin:0.3.3:build (build-image) @ example-project ---
[INFO] Skipping docker build
[INFO]
[INFO] --- docker-maven-plugin:0.3.3:tag (tag-image) @ example-project ---
[INFO] Creating tag example.com/example-tag:1.0-SNAPSHOT from example-project

**Comment by cthiebault** [comment]
Use `skipDockerTag` property.
