### ISSUE TITLE
Please add support for resource exclude to docker plugin

### ISSUE THREAD

**Issue by ayen-tibco** [spotify/docker-maven-plugin#175]
For some reason the plugin copies everything in my dockerDirectory to the Target directory even with exclude statements included. Is resources exclude feature not implemented in the plugin?

    <plugin>
    <groupId>com.spotify</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.3.10-SNAPSHOT</version>
        <executions>
                <execution>
                        <phase>package</phase>
                        <goals>
                                <goal>build</goal>
                        </goals>
                </execution>
        </executions>
        <configuration>
                <imageName>ep/${project.artifactId}</imageName>
                <baseImage>centos:7</baseImage>
                <dockerDirectory>${project.basedir}</dockerDirectory>
                <pushImage>false</pushImage>
                <resources>
                        <resource>
                                <targetPath>/</targetPath>
                                <directory>/root/eppoc/dtm-docker</directory>
                                <excludes>
                                        <exclude>java/**/*</exclude>
                                        <exclude>target/**/*</exclude>
                                        <exclude>pom.xml</exclude>
                                </excludes>
                                <include>Dockerfile</include>
                        </resource>
                </resources>
 </configuration>
    </plugin>

**Comment by mattnworb** [comment]
No, the plugin does not look at / support the excludes element in the `<resource>`. See  #25 for some more info on why not and https://github.com/spotify/docker-maven-plugin/issues/25#issuecomment-88796978 for how you can use maven-resources-plugin as a workaround.

**Comment by Bessonov** [comment]
@ayen-tibco Yes, this is a problem of plugin. It's just copy everything from dockerDirectory even with include/exclude, waste time and space. To workaround I do following stuff.

Copy filtered Dockerfile to target/docker (this also creates a docker directory, it's important):

    <resource>
    	<directory>${project.build.sourceDirectory}/conf</directory>
    	<targetPath>${project.build.directory}/docker</targetPath>
    	<filtering>true</filtering>
    	<includes>
    		<include>**/Dockerfile</include>
    	</includes>
    </resource>

Then I set target/docker as dockerDirectory and just include my jar artefact:

	<configuration>
		<imageName>${docker.image.prefix}/${project.artifactId}</imageName>
		<dockerDirectory>${project.build.directory}/docker</dockerDirectory>
		<imageTags>
			<imageTag>${project.version}</imageTag>
			<imageTag>latest</imageTag>
		</imageTags>
		<resources>
			<resource>
				<targetPath>/</targetPath>
				<directory>${project.build.directory}</directory>
				<includes>
					<include>${project.build.finalName}.jar</include>
				</includes>
			</resource>
		</resources>
	</configuration>

Afterwards I have just two desired files: Dockerfile and my jar file.

**Comment by ayen-tibco** [comment]
Right, that is what I ended up doing. But thanks for official workaround solution as this well help others.

**Comment by poliveira89** [comment]
@Bessonov how it would look the full `pom.xml`? 

Because I did not understand where do you write the first `<resource>`  unless you configure two `<resource>` inside the docker `<plugin>`.

**Comment by Bessonov** [comment]
@poliveira89 I don't have source code now. The first `<resource>` is for  [maven-resources-plugin](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html).
