### ISSUE TITLE
ClientProtocolException (Windows 10 using Docker Toolbox)

### ISSUE THREAD

**Issue by Jdruwe** [spotify/docker-maven-plugin#177]
I am trying to build a docker image using the docker-maven-plugin but things aren't really working out. At first I got this exception: 

```
org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375
```

I found out that I had to create an env. variable to fix this (https://github.com/spotify/docker-maven-plugin/issues/135): 

```
set DOCKER_HOST=set DOCKER_HOST=tcp://192.168.99.100:2376
```

[![docker_host](http://i.stack.imgur.com/Wp6IQ.png)](http://i.stack.imgur.com/Wp6IQ.png)

So after setting that env. variable I keep getting this ClientProtocolException:

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default-cli) on project docker_micro_maven: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException: The server failed to respond with a valid HTTP response
```

I have no idea how I could fix this, any input would be greatly appreciated.

**Comment by davidxia** [comment]
@Jdruwe 
You usually need other env vars too:

```
env | grep -i docker

DOCKER_CERT_PATH=/Users/dxia/.docker/machine/machines/1.8.3
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=1.8.3
DOCKER_TLS_VERIFY=1
```

**Comment by Jdruwe** [comment]
Indeed that fixed it, in my cased I am now setting the following:

set DOCKER_HOST=tcp://192.168.99.100:2376
set DOCKER_MACHINE_NAME=default
set DOCKER_TLS_VERIFY=1
set DOCKER_TOOLBOX_INSTALL_PATH=C:\Program Files\Docker Toolbox
set DOCKER_CERT_PATH=C:\Users\myuserhere\.docker\machine\machines\default

**Comment by wburgers** [comment]
@davidxia Could that be made more clear in the readme somewhere?
Works perfectly after setting these env vars, but the readme is not quite clear.

Thanks

**Comment by wagner-wutzke** [comment]
It fixed the problem for me too.
Thanks for sharing!

**Comment by doubl3p** [comment]
i fixed this on this way (my answer is from DOUBL3P): 

http://stackoverflow.com/questions/34815411/docker-maven-plugin-clientprotocolexception-windows-10-using-docker-toolbox/41621300#41621300

fixes this by:
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.4.13</version>
				<configuration>
					<imageName>yourImageName</imageName>
					<dockerDirectory>src/main/docker</dockerDirectory>
					<dockerHost>https://192.168.99.100:2376</dockerHost>					                                   <dockerCertPath>/Users/your_user/.docker/machine/machines/default</dockerCertPath>
					<resources>
						<resource>
							<targetPath>/</targetPath>
							<directory>${project.build.directory}</directory>
							<include>${project.build.finalName}.jar</include>
						</resource>
					</resources>
				</configuration>
			</plugin>

Important are these two tags:

    <dockerHost>https://192.168.99.100:2376</dockerHost>
    <dockerCertPath>/Users/your_user/.docker/machine/machines/default</dockerCertPath>

I am using a dockerfile, which path you have to define with this tag:

    <dockerDirectory>src/main/docker</dockerDirectory>  

Now you can build your jar and generate docker image via: 
mvn package docker:build

**Comment by hongliangpan** [comment]
docker-machine env default

set DOCKER_HOST=tcp://192.168.99.100:2376
set DOCKER_MACHINE_NAME=default
set DOCKER_TLS_VERIFY=1
set DOCKER_TOOLBOX_INSTALL_PATH=C:\Program Files\Docker Toolbox
set DOCKER_CERT_PATH=C:\Users\panhl-a\.docker\machine\machines\default

**Comment by Vespira** [comment]
With the new virtualization method on Windows 10 (using Microsoft HyperV instead of a Docker Machine over VirtualBox), Maven Docker plugin try to reach by default an insecure Docker daemon. If you are in development env, you can also run docker engine without TLS enabled and Maven will then be able to reach your Moby VM mapped to localhost. Using self-signed certificate to secure a Docker daemon doesn't work well as far as I can rememer, but i'll try again soon, to etablish a TLS link.
