### ISSUE TITLE
`docker:build -DpushImage` should also push any additional tags that were added with `imageTags`

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-maven-plugin#180]
`docker:build` will tag the just-built image with any extra tags defined in `imageTags` but when `-DpushImage` is enabled only the main image name is pushed. Ideally `docker:build -DpushImage` should push all tags on the just built image.

**Comment by mattnworb** [comment]
cc @pettermahlen 

#127 offers another way to tackle this - an extra flag `-DpushImageTags` to `docker:build -DpushImage` will also push any tags specified in `<imageTags>`

**Comment by calvernaz** [comment]
+1
