### ISSUE TITLE
support for docker command line option --build-arg

### ISSUE THREAD

**Issue by solagappan** [spotify/docker-maven-plugin#184]
Hi,

Do we have support for "--build-arg" , can you please provide the usage doc if supported. We have http_proxy in our env and I want to use this option in docker build command.

Thanks,
Subbu

**Comment by mattnworb** [comment]
No, the build-arg feature is not yet supported in this plugin. We don't make use of this feature internally at Spotify so I do not think we are likely to add this any time soon, but PRs are welcome.

Personally I am not sure how well this feature of docker fits in with maven and this plugin as I am not sure where the runtime value of the arg will come from - system properties specified on the command line, maven profiles, etc? You can accomplish much of the same thing already today with plain [resource filtering](http://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html) your Dockerfile.

**Comment by balazsmaria** [comment]
I don't understand your last sentence, what can we achieve with resource filtering? I'd also need to pass our much loved and respected http_proxy as build-arg.

**Comment by mattnworb** [comment]
addressed in #198

**Comment by solagappan** [comment]
Thanks !
