### ISSUE TITLE
support Dockerfile COPY command

### ISSUE THREAD

**Issue by hailong226** [spotify/docker-maven-plugin#193]
`<resources>
                                            <resource>
                                                <targetPath>/</targetPath>
                                                <directory>${project.build.directory}</directory>
                                                <include>${project.build.finalName}.zip</include>
                                            </resource>
                                        </resources>`
this use dockerfile add, can support the copy?

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
