### ISSUE TITLE
support specifying username and password for private registries in pom

### ISSUE THREAD

**Issue by a-buck** [spotify/docker-maven-plugin#195]
At the moment you have to specify the username and password in a `<server>` block within the `settings.xml`, then reference it with a `serverId` property under `<configuration>` in the `pom.xml`.

We would like to pull an image from a private docker repository which requires authentication. It's not a sensitive username/password, therefore we would like to be able to specify the credentials in the pom instead of relying on users to update their settings.xml:

```
<configuration>
  <username>my-username</username>
  <password>my-password</password>
  [...]
```

If you agree with this I would love to have a go at implementing it please.

**Comment by aditzel** [comment]
Are there any plans to support this? This type of feature becomes increasingly useful when integrating builds into a Jenkins pipeline workflow.

**Comment by mattnworb** [comment]
#339 will make it so that if your username and password appears in the ~/.docker/config.json, then it will be used transparently by the plugin without needing to put anything in your pom.xml.
