### ISSUE TITLE
Support for --rm=false option

### ISSUE THREAD

**Issue by ggerbaud** [spotify/docker-maven-plugin#196]
## Description

On my CI tool I have btrfs issues like this
`Driver btrfs failed to remove root filesystem xxx: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for xxx: operation not permitted`
So it should be great to add support for `--rm=false`. 
Clean up intermediate container wouldn't be an issue here as the CI environment is destroy after each build (CircleCI)
## How to reproduce

Use the plugin in CircleCI

**Comment by mattnworb** [comment]
Which goal of the plugin are you executing that results in a `--rm=true` command?

**Comment by ggerbaud** [comment]
`docker:build`
I should have mentioned it

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
