### ISSUE TITLE
Cannot create Image

### ISSUE THREAD

**Issue by nandhusriram** [spotify/docker-maven-plugin#197]
## Description

Not able to create docker image from maven command.
[Add feature/bug description here]
## How to reproduce

mvn package docker:build
[Add steps on how to reproduce this issue]
## What do you expect

[Describe what do you expect to happen]
## What happened instead

[Describe the actual results]
## Software:
- docker version: v1.10.2 
- docker-maven-plugin version:0.41
- maven version: 3.2.5
## Full backtrace

``` text
[Paste full backtrace here]
[DEBUG] Writing Dockerfile:
FROM java
ADD /abc.jar //
ENTRYPOINT ["java", "-jar", "/abc.jar"]
[INFO] Building image MyIMAGE/abc
[DEBUG] Auth Config null
[DEBUG] Registry Config Json {"":{"serveraddress":"","password":"","auth":"","email":"","username":""}}
[DEBUG] Registry Config Encoded eyIiOnsic2VydmVyYWRkcmVzcyI6IiIsInBhc3N3b3JkIjoiIiwiYXV0aCI6IiIsImVtYWlsIjoiIiwidXNlcm5hbWUiOiIifX0=
Mar 02, 2016 6:29:08 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://192.168.99.100:2376: Broken pipe
```

**Comment by mattnworb** [comment]
>  (java.net.SocketException) caught when processing request to {s}->https://192.168.99.100:2376: Broken pipe

sounds like an issue communicating with your docker daemon. It's not clear that this has anything to do with the plugin itself.

**Comment by FraBle** [comment]
+1

**Comment by megglos** [comment]
I encountered this issue when I used uppercase characters in the image name, try to use lowercase only:
MyIMAGE/abc => my-image/abc

**Comment by flungo** [comment]
Can the plugin automatically `toLowerCase()` the `imageName` to avoid this problem and allow any properties to be used. Seems like a pain to use the `gmaven-plugin` to do this.
