### ISSUE TITLE
I want to provide a simple reference implementation of the plugin usage

### ISSUE THREAD

**Issue by sid-saddala** [spotify/docker-maven-plugin#200]
## Description

I want to provide a simple reference implementation of the plugin usage. I tried the plugin and documented the usage steps and the sample code. Instructions in [ReadMe](https://github.com/sid-saddala/TryDockerMavenPlugin/blob/master/README.md). Source code is [here](https://github.com/sid-saddala/TryDockerMavenPlugin). I thought it can be helpful for starters to learn using the plugin.
## How to reproduce

Not Applicable
## What do you expect

I thought my repo can help those who want to quickly try the plugin. So, contributing.
## What happened instead

Not Applicable
## Software:
- docker-maven-plugin version: 0.4.2
- maven version: 3.3

**Comment by chariut** [comment]
Thanks for this example Sid. If you could provide example of what changes would be required in Dockerfile to automatically build the image in docker hub, it would be a great help.

**Comment by davidxia** [comment]
@sid-saddala thanks. Feel free to open a PR to improve the docs. I'll close this in the meantime.
