### ISSUE TITLE
How to skip Docker build when image building is attached to package phase?

### ISSUE THREAD

**Issue by cthiebault** [spotify/docker-maven-plugin#203]
I configured my `pom.xml` so Docker image is built & tagged on `package` phase and pushed on `deploy` phase.

Is there a way to skip Docker image build and Docker push? 
Something like `-DskipDockerBuild` and `-DskipDockerPush`? 

Here is my config:
```
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <configuration>[...]</configuration>
  <executions>
    <execution>
      <id>build-image</id>
      <phase>package</phase>
      <goals>
        <goal>build</goal>
      </goals>
    </execution>
    <execution>
      <id>tag-image</id>
      <phase>package</phase>
      <goals>
        <goal>tag</goal>
      </goals>
      <configuration>[...]</configuration>
    </execution>
    <execution>
      <id>push-image</id>
      <phase>deploy</phase>
      <goals>
        <goal>push</goal>
      </goals>
      <configuration>[...]</configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by cthiebault** [comment]
After reading https://github.com/spotify/docker-maven-plugin/issues/187, it seems that we can:
* skip Docker build with `-DskipDockerBuild`  
(https://github.com/spotify/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/BuildMojo.java#L117)
* skip Docker tag with `-DskipDockerTag`  
(https://github.com/spotify/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/TagMojo.java#L59)
 
But I did nit find a way to skip Docker push...

**Comment by derekbassett** [comment]
What needs to happen to get a new release of this plugin?

**Comment by mattnworb** [comment]
@derekbassett version `0.4.12` was released 3 days ago and contains all of the latest commits.
