### ISSUE TITLE
Docker-Compose support

### ISSUE THREAD

**Issue by sidgoyal** [spotify/docker-maven-plugin#214]
How open would you guys be to add support for docker-compose support ? 

I can help out with the code as well.

**Comment by mattnworb** [comment]
@sidgoyal I suppose it would depend on what that support looks like, or how much it changes the existing goals. At Spotify we don't use Docker Compose so I am not super familiar with what support would look like. If the changes aren't invasive and/or don't change how the existing plugin goals work (build, tag, push etc) then we would be happy to review any PRs.

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
