### ISSUE TITLE
Is there a support for --build-arg?

### ISSUE THREAD

**Issue by liyaka** [spotify/docker-maven-plugin#226]
Add support for --build-arg:
I would expect to have a option to define something like this under configuration:
<buildArguments>
   <RELEASE_DATE>${today}</RELEASE_DATE>
   <LICENSE>${my_license}</LICENSE>
</buildArguments>

Thanks

**Comment by mattnworb** [comment]
This was added in #184 and should be available in the most recent version of the plugin
