### ISSUE TITLE
Ability to specify target filename

### ISSUE THREAD

**Issue by jmkgreen** [spotify/docker-maven-plugin#236]
## Description

Feature: Ability to specify target filename for the `jar` command to execute.

Right now it is only possible copy the project's filename into a folder. This means downstream docker-compose files can run the containers but cannot override the `entryPoint` without knowing the names of the artefacts involved.

Example: `entryPoint` ends up as `java -jar /my-final-name-version-SNAPSHOT.jar`

Right now I have about a dozen containers in a compose file. And I want to override the -Jmx settings. AFAICT I need to supply the full entrypoint for each container and that means not only knowing the Maven level project file name but also the Maven project version. That's a lot of knowledge spreading downstream that could change.

I tried specifying a `targetPath` that was in fact a filename but it still gets treated as a folder within the container.

**Comment by mattnworb** [comment]
I might be misunderstanding, but are you trying to control the name of the jar file produced by `maven-jar-plugin`? You can use `build.finalName`.

**Comment by jmkgreen** [comment]
No, I'd like to control the name of the COPY target. So if `build.finalName` is `my-project-1.7.5-SNAPSHOT` I would like instead to copy this JAR into `/runtime.jar` that that the `entrypoint` becomes `java -jar /runtime.jar` instead of `java -jar /my-project-1.7.5-SNAPSHOT.jar`.

Thus across versions the `entrypoint` can remain unchanged.

**Comment by mattnworb** [comment]
Sorry for the delay in responding, but I think the best bet in this situation is to supply your own Dockerfile to the plugin. I think there is a limit to how customizable it makes sense to allow the auto-generated Dockerfile to be.

**Comment by lcamilo15** [comment]
I was able to accomplish this. The idea is to have a  ${basedir}/Dockerfile that maven uses as resource filtering and includes it within ${basedir}/src/main/docker/. 

[Resource Filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html#)
[Copying Resource](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html#)

Please make sure that ${basedir}/src/main/docker/ exists

on your pom.xml

```xml
<plugin>
	<artifactId>maven-resources-plugin</artifactId>
	<version>3.0.2</version>
	<executions>
		<execution>
			<id>copy-resources</id>
			<phase>validate</phase>
			<goals>
				<goal>copy-resources</goal>
			</goals>
			<configuration>
				<outputDirectory>${basedir}/src/main/docker/</outputDirectory>
				<resources>
					<resource>
						<directory>${basedir}</directory>
						<includes>
							<include>Dockerfile</include>
						</includes>
						<filtering>true</filtering>
					</resource>
				</resources>
			</configuration>
		</execution>
	</executions>
</plugin>
```

In ${basedir}/Dockerfile, Please note we are using @VAR-NAME@ instead of ${VAR-NAME}
```docker
FROM java:8
VOLUME /tmp
ADD @project.build.finalName@.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 8888
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```
