### ISSUE TITLE
Support an optional init script

### ISSUE THREAD

**Issue by jmkgreen** [spotify/docker-maven-plugin#237]
Suggestion - allow the writing of a shell script into the container that is launched by the `entrypoint`.

The shell script would then be responsible for launching the java process. This allows for easy interpolation of things like JAVA_OPTS as an environment variable much like Tomcat.

**Comment by mattnworb** [comment]
If you supply your own Dockerfile, this sort of thing should be pretty easy to accomplish. The part of the plugin that generates a Dockerfile for you only really for convenience and I think we would be wary of adding more logic to it.
