### ISSUE TITLE
mvn docker:build returns 500: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by aoxa** [spotify/docker-maven-plugin#239]
## Exception caught: Request error: POST unix://localhost:80/v1.12/build?t=aaa:

I'm trying to build an image but am unable to do so.
My env:
- OS: ubuntu 14.04
- Maven 3.0.5
- jdk 7
Docker:
 docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

I have no logs whatsoever, I've search in /var/logs/**/docker.log and nothing, ran locate docker, and no log file either.
The service is running, call 
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

I've tried:
1- rename the image to aaa (lower case, as a previous reported issue)
2- sudo mvn docker:build
3- Added DOCKER_OPTS to -D to see if that would create the logs... no joy.

Thanks,
Pedro.

**Comment by aoxa** [comment]
The Dockerfile was incorrect. Solved.

**Comment by cradules** [comment]
What do you mean by incorrect?

**Comment by Amithahiriadaka** [comment]
To isolate I changed the image name in pom.xml . I could build  docker image after that.
I will update my observation.


I<groupId>com.spotify</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <version>${docker.maven.plugin.spotify.version}</version>
            <configuration>
              <imageName>amithas_creditservice</imageName>
              <baseImage>java</baseImage>
              <entryPoint>["java", "-jar", "/${project.build.finalName}.jar"]</entryPoint>
              <resources>
                <resource>
                  <targetPath>/</targetPath>
                  <directory>${project.build.directory}</directory>
                  <include>${project.build.finalName}.jar</include>
                </resource>
              </resources>
            </configuration>
          </plugin>
