### ISSUE TITLE
plugin fails to read property "docker"

### ISSUE THREAD

**Issue by kvfedorov** [spotify/docker-maven-plugin#24]
This is minor issue and I am posting here for others to be aware.

Plugin fails when "docker" property presents in context:
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.0.21:build (default) on project <....>: Exception caught: system properties: docker has type STRING rather than OBJECT

I've defined my own property with name "docker" and it led to a crash. It is easy to fix by using different name, but error was pretty strange and confusing (as I was not aware of plugin uses some properties too and uses typesafe config to parse them). 

Would be good to have some sort of namespace specific to plugin to avoid name clashing with other people properties....

Otherwise great work guys ;)

**Comment by davidxia** [comment]
@kvfedorov Thanks, namespacing is a good idea. Sorry for the confusion.

**Comment by davidxia** [comment]
Hm I'm not going to do this now as it's backwards incompatible :(

**Comment by mattnworb** [comment]
Since changing the name of the property would break previous versions, I'll simply add a note to the README to warn people about this. Thanks for the heads up @kvfedorov (and sorry for the very delayed response).
