### ISSUE TITLE
build fails in dockerhub

### ISSUE THREAD

**Issue by chariut** [spotify/docker-maven-plugin#241]
Build failed in dockerhub when plugin used as shown in https://spring.io./guides/g/spring-boot-docker:

INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
[0m[91mJun 17, 2016 7:33:45 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[0m[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.139 s
[INFO] Finished at: 2016-06-17T19:33:45+00:00
[INFO] Final Memory: 28M/68M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project restDemo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 
## How to reproduce

 

FROM maven:3.3-jdk-8
WORKDIR /
ADD pom.xml /pom.xml
ADD settings.xml /settings.xml
ADD docker/docker /etc/sysconfig/docker 
RUN pwd
ADD src/main/docker/Dockerfile /src/main/docker/Dockerfile
RUN mvn clean package docker:build
## What do you expect

dockehub successully build image
## What happened instead

build failed with the below mentioned exception
## Software:
- docker version: dockerhub
- docker-maven-plugin version: 0.4.10
- maven version: FROM maven:3.3-jdk-8
## Full backtrace

``` text
partial-list:

INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
[91mJun 17, 2016 7:33:45 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.139 s
[INFO] Finished at: 2016-06-17T19:33:45+00:00
[INFO] Final Memory: 28M/68M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project restDemo: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 
```

**Comment by chariut** [comment]
pom file attached here: [pom.xml.txt](https://github.com/spotify/docker-maven-plugin/files/321205/pom.xml.txt)

**Comment by chariut** [comment]
Here is the pom file: [pom.xml.txt](https://github.com/spotify/docker-maven-plugin/files/321218/pom.xml.txt)

**Comment by iron-hulk** [comment]
Just a suggestion if you are running on mac or windows and using boot2docker, make sure you start up the docker daemon first and then run the command from the command where the daemon was started. I ran into the issue on my mac however I just had to run the mvn package docker:build from that same terminal it was opened in.

**Comment by mattnworb** [comment]
> INFO: Retrying request to {}->unix://localhost:80

this more than likely means that you have not configured the plugin to talk to your DOCKER_HOST, or that DOCKER_HOST is not set

**Comment by cradules** [comment]
The error refers to the fact that the user you are using dose not has the right to access docker proccess. Add the user  to docker group. 

usermod -a -G <username> docker

Good luck!
