### ISSUE TITLE
Support include of directories

### ISSUE THREAD

**Issue by nkavian** [spotify/docker-maven-plugin#243]
## Description

When creating an image I want to include a jar as well as a directory of dependencies.

```
<includes>
    <include>${project.build.finalName}.jar</include>
    <include>dependencies</include>
</includes>
```

The second line for `dependencies` is ignored.  However if I specify an expression it creates a Dockerfile with 1 line per jar file within `dependencies`.

```
<includes>
    <include>${project.build.finalName}.jar</include>
    <include>dependencies/*</include>
</includes>
```

Since there are more than 120 jar files in that folder, the Dockerfile has more than 120 ADD statements.  Eventually at "Step 119" the plugin generates this error in maven: [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project cubeone-server-jar: Exception caught: max depth exceeded -> [Help 1]
## What do you expect

It would be great if the plugin supported `include` of directories to add.  Docker supports it and this plugin can as well.

When using `dependencies/*` in docker command line, it works as expected, but using it in the pom.xml the plugin expands it out to a list of files instead.  Don't expand out the list.
## Software
- docker version: 1.12
- docker-maven-plugin version: 0.4.10
- maven version: 3.x

**Comment by gonciarz** [comment]
+1
