### ISSUE TITLE
Enviroment variables are executed in alphabetical order

### ISSUE THREAD

**Issue by gavioto** [spotify/docker-maven-plugin#244]
## Description

Envieroment variables "ENV" are executed in alphabetical order in the DOCKERFILE.
The order used in pom.xml is not maintained in Dockerfile, so possible confusion.

I see [here](https://github.com/spotify/docker-maven-plugin/blob/100b12964c2112e79ffa536cf653fcc5c4b64f3e/src/main/java/com/spotify/docker/BuildMojo.java#L588
) it is using a sorted collection. 

## How to reproduce

In a POM with 
```
<env>
  <ENV_2>cache</ENV_2>
  <ENV_1>-Denv2value=${ENV2}<ENV_1>
<env>
```
the generated Dockerfile is
```
ENV ENV_1 -Denv2value=${ENV2}
ENV ENV_2 cache
```
Finally, the image is created with blank value 
```
-Denv2value=
```
## What do you expect

ENV order in POM should be maintained. On the other hand, it should be documented.

## Workaround

Escape env variable using value in container with '$$'
```
-Denv2value=\${ENV2}
```
it should do the trick

## Software:

- docker version: 1.11.1
- docker-maven-plugin version: 0.4.10
- maven version: 3.3.3

**Comment by mattnworb** [comment]
If you have a need to maintain a certain ordering of statements in your Dockerfile, I would suggest writing your own and pointing the plugin towards that (with the `dockerDirectory` configuration parameter) rather than using the convenience function of the plugin that generates a file for you.

**Comment by gavioto** [comment]
I think this behauvior is not as usual with any enviroment variables on linux shell, or window shell or any other shell. What are the reason to mantain this behauvior? Only to understand. Thanks
