### ISSUE TITLE
DEBUG logging level outputs private registry password

### ISSUE THREAD

**Issue by mryan43** [spotify/docker-maven-plugin#245]
## Description

When using a private registry with DEBUG log level enabled (mvn -X), the password used to access the registry from the settings.xml file is displayed 2 times in clear in the logs (and 1 time in base64) :

[DEBUG] Auth Config AuthConfig{username=username, password=thepassword, email=user@organization.com, serverAddress=https://private.registry.organization.com/v2/}
[DEBUG] Registry Config Json {"https://private.registry.organization.com/v2/":{"serveraddress":"https://private.registry.organization.com/v2/","password":"thepassword","auth":"","email":"user@organization.com","username":"username"}}
[DEBUG] Registry Config Encoded (the same thing encoded in base64 !)
## What do you expect

Password value should be replaced with ****\* or [HIDDEN]
## What happened instead

They are printed in the logs or on the screen
## Software:
- docker-maven-plugin version: 0.4.10
- maven version: 3.3.9

**Comment by wheredevel** [comment]
This is a major security flaw.  
Is it going to be addressed?

**Comment by mattnworb** [comment]
This is an issue with the underlying docker-client library. I've created an issue there.

**Comment by wheredevel** [comment]
Can you post the link to the issue?
