### ISSUE TITLE
Support for 'docker run/stop' to start/stop containers

### ISSUE THREAD

**Issue by Malu44** [spotify/docker-maven-plugin#250]
## Description

Are there plans to support 'docker run/stop' to start/stop containers?
I'll see in the 'docker-client' there are methods for 'createContainer' etc.

Thankx,
Malu

**Comment by mattnworb** [comment]
Sorry for the delayed response @Malu44 - we don't have any plans ourselves to add a stop or start goal to the plugin as we don't really have a need, but I'd be happy to review/merge any PR that added such a thing.

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
