### ISSUE TITLE
Add possibility to provide options for build docker

### ISSUE THREAD

**Issue by kouKatsumi** [spotify/docker-maven-plugin#251]
## Description

I would like to be able to specify flags, doesn't matter if by text or a building in plugin flag, that are specified here: https://docs.docker.com/engine/reference/commandline/build/
I'm specifically interested in -q, to quite docker output.
## What do you expect

I would like to be able to add at least -q flag to building image phase.
## What happened instead

No such option

**Comment by jpettersson** [comment]
+1

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
