### ISSUE TITLE
Wildcard (*) character issues in .dockerignore

### ISSUE THREAD

**Issue by castillobgr** [spotify/docker-maven-plugin#255]
## Description

Building my image with the plugin fails with

``` sh
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project hdmap-html-visualizer: Exception caught: Illegal char <*> at index 8: target\\*.original -> [Help 1]
```

which is a rule in my .dockerignore file: `target/*.original`
## How to reproduce

Create a .dockerignore file in the specified dockerDirectory with an entry containing the wildcard character.
Then run `mvn clean package docker:build`
## What do you expect

The image is built without problems, just like with `docker build ...`
## What happened instead

The plugin encounters an error because of the .dockerignore file

``` sh
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project hdmap-html-visualizer: Exception caught: Illegal char <*> at index 8: target\\*.original -> [Help 1]
```
## Software:
- docker version:1.11.2
- docker-maven-plugin version: 0.4.11
- maven version: 3.3.9
## Full backtrace

See above

**Comment by guzmo** [comment]
We get the same on windows machines. We need to ignore "*-sources.jar" and "*-javadoc.jar" to make releases but then the (windows) developers needs to modify the .dockerignore to be able to build while developing.

**Comment by mattnworb** [comment]
I am having trouble reproducing this. 

@castillobg can you paste the full exception stacktrace that you get if you add the `-e` flag to `mvn`?

Also what OS are you using, and how do you run docker (docker-machine, docker for mac, native docker, etc)

**Comment by castillobg** [comment]
@guzmo sorry, this was a while ago and I can't reproduce it either :(
I now have a .maven-dockerignore with the same rules and it works just fine. For what it's worth, I'm running Windows 10, with Docker set up with Docker for Windows.
Maybe @mattnworb can continue with the feedback!

**Comment by guzmo** [comment]
@castillobgr  Ok, we can try to upgrade the docker-maven plugin or maybe it is because we are running an old docker version.
