### ISSUE TITLE
Possibility to add Multiple <cmd>

### ISSUE THREAD

**Issue by driverpt** [spotify/docker-maven-plugin#259]
## Description

Possibility to add Multiple <cmd> through Maven.

e.g.:

<cmds>
  <cmd>apk add --upgrade dockerize</cmd>
  <cmd>touch /opt/${project.build.finalName}.jar</cmd>
</cmds>
## Software:
- docker version: Docker version 1.12.0, build 8eab29e, experimental
- docker-maven-plugin version: 0.4.11
- maven version: Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)

**Comment by mattnworb** [comment]
The simplest way to do this today without any updates to the plugin is to [supply a Dockerfile](https://github.com/spotify/docker-maven-plugin#use-a-dockerfile) of your own.

**Comment by driverpt** [comment]
@mattnworb , how to i inject ${project.build.finalName}.jar within the Dockerfile ?

**Comment by mattnworb** [comment]
You can use some sort of resource filtering on the Dockerfile within your build, or you can set `<build><finalName>` for your jar to remove the version string so that the packaged jar always has the same name.

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
