### ISSUE TITLE
How to copy & rename a resource?

### ISSUE THREAD

**Issue by rodlogic** [spotify/docker-maven-plugin#26]
I am using a Dockerfile configuration and would like to have a standard name for the artifact I am deploying to the image (e.g. myapp.war). The resource entry only allows me to copy the artifact. I understand I can change the pom to change the final artifact id, but I would not like to do that.

```
<resource>
	<targetPath>/</targetPath>
	<directory>${project.build.directory}</directory>
	<include>${project.build.finalName}.${project.packaging}</include>
</resource>
```
And my Dockerfile:
```
COPY /myapp.war /tomcat/webapps/
```

**Comment by davidxia** [comment]
@rodlogic do you still need help or can i close this?

**Comment by jorgemoralespou** [comment]
Hi,
I have the same issue, and I would really appreciate your help, a sample configuration for this, as I can not make it to work.

**Comment by moimael** [comment]
We also have the same problem. We use docker-maven-plugin with failsafe to run HTTP REST API integration test against autodeployed war in docker tomcat container and having version dependant url is a huge issue.

**Comment by moimael** [comment]
Ok there is a better way, just name your war: <app_name>#<version> and it will be deployed without version in the context.

**Comment by ggtools** [comment]
I had the same issue and I solved this issue by using a first plugin to copy/rename my jar to a generic name and then use the docker maven plugin from this generic name.

You can use either `copy-rename-maven-plugin` to do this first part or my own `regex-copy-maven-plugin` which is a little bit more flexible.

For instance copy removing the version from the generated artifact:

```
                        <plugin>
                            <groupId>net.ggtools.maven</groupId>
                            <artifactId>regex-copy-maven-plugin</artifactId>
                            <version>0.1.4</version>
                            <configuration>
                                <sourceDirectory>${project.build.directory}</sourceDirectory>
                                <destinationDirectory>${project.build.directory}</destinationDirectory>
                                <source>^(${project.name}).*?\.(${project.packaging})$</source>
                                <destination>{1}.{2}</destination>
                                <overwrite>true</overwrite>
                            </configuration>
                            <executions>
                                <execution>
                                    <id>regex-copy-docker-jar</id>
                                    <phase>package</phase>
                                    <goals>
                                        <goal>regex-copy</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
```

**Comment by erindru** [comment]
For anyone else who comes across this issue, there a simpler solution. Just add the following to your `<plugin>` declaration:

```xml
		        <runs>
		        	<run>mv /usr/local/tomcat/webapps/${project.build.finalName}.war /usr/local/tomcat/webapps/name-you-actually-want.war</run>
		        </runs> 
```

Much easier than trying to make Maven name it correctly to begin with
