### ISSUE TITLE
I can't use the plugin exclusively on a child module

### ISSUE THREAD

**Issue by jacklaplante** [spotify/docker-maven-plugin#263]
## Description

I want to use this docker-maven-plugin exclusively on one child module of my maven project.

## How to reproduce

I tried putting the plugin only inside the pom of the child module. When I did `mvn clean package docker:build` it failed:

`[ERROR] No plugin found for prefix 'docker' in the current project and in the plugin groups`

If I put the plugin anywhere inside the parent pom (in `<plugins>` or `pluginManagement`) then it assumes that I'm making a docker container from the parent module and every child module.

## What do you expect

I only want one container from one child module.

## Software:

- docker version: 1.11.2
- docker-maven-plugin version: 0.4.11
- maven version: 3.3.9

**Comment by mattnworb** [comment]
I believe you can tackle this in one of two ways 

1. you can configure the plugin in the parent pom's `<plugins>` section but default the plugin configuration to skip the docker build, and override that in the child module to not skip

2. configure it only in the child module and bind the `build` goal to the `package` phase.

**Comment by jacklaplante** [comment]
I'm trying to get the docker build to skip by default by adding `<skip>true</skip>` to `<configuration>` but that isn't working. Is there a different way to do it?

**Comment by mattnworb** [comment]
The [configuration property is named `skipDockerBuild`](https://github.com/spotify/docker-maven-plugin/blob/0d8aa7531da3ba29c4aeee4897411ec7ea34c711/src/main/java/com/spotify/docker/BuildMojo.java#L112-L117), not `skip`.

**Comment by jacklaplante** [comment]
Thanks for the help! It's very much appreciated.

**Comment by sachinlala** [comment]
I am trying this approach: 
_configure it only in the child module and bind the build goal to the package phase_

But still getting the same error.

Here is the snippet of how the plugin is sourced in the child module:
`

            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.11</version>
                <configuration>
                    <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                    <dockerDirectory>.</dockerDirectory>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                </configuration>
                <executions>
                    <execution>
                        <id>docker-build</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
`

Please can you review ?

**Comment by Ademord** [comment]
Any *clear* help on this on how to effectively build the docker image for a multi-module app?

**Comment by mattnworb** [comment]
@sachinlala 

> But still getting the same error.

can you clarify which error you are referring to?
