### ISSUE TITLE
Add documentation for configuration properties that IDE tooling can see

### ISSUE THREAD

**Issue by davidmichaelkarr** [spotify/docker-maven-plugin#265]
Typically, Maven plugins are built to work with IDEs (Eclipse, for instance) such that if I add the "<configuration>" block to the plugin and then enter "<", I can step through the allowed configuration properties and see the tooltip that describes the configuration property. Presently, what shows for all of the properties for this plugin just has the name and the type.

**Comment by mattnworb** [comment]
I am not sure how Eclipse derives that info, but it works already for IntelliJ:

![image](https://cloud.githubusercontent.com/assets/113840/18633861/5a4248cc-7e4c-11e6-9987-eee4cde9bff3.png)

I would hope that any IDE would base it's auto-complete / documentation on the [javadoc comments for `@Parameter`-annotated methods](https://github.com/spotify/docker-maven-plugin/blob/49dedf7b0bc6b798f3cb96566a4bbba21173df42/src/main/java/com/spotify/docker/BuildMojo.java#L104-L109) - as I believe the Maven build process generates a plugin.xml that is included in the JAR for the plugin.

If you find that Eclipse needs some other sort of metadata about the plugin I'd be happy to merge a PR that adds whatever Eclipse-specific info is needed.
