### ISSUE TITLE
Failed to build the Docker image

### ISSUE THREAD

**Issue by Sriharsha1693** [spotify/docker-maven-plugin#267]
## Description

I have initially executed the command mvn clean install package on the Root Hygieia, 
api.jar has been successfully created in the target folder.

Then, Installed mongo db able to connect the api collector with the dashboard db

Then, 
when I tried to execute the below command for Docker image, 

mvn clean package -pl api docker:build

facing the Build failure issue

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- docker version: [Add docker version here, client and server]
- docker-maven-plugin version: [Add docker-maven-plugin version here]
- maven version: 3.3.9

## Full backtrace

```text
Results :

Tests run: 114, Failures: 0, Errors: 0, Skipped: 3

[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ api ---
[INFO] Building jar: D:\Hygieia-master\api\target\api.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.5.RELEASE:repackage (default) @ api ---
[INFO]
[INFO] --- docker-maven-plugin:0.4.10:build (default-cli) @ api ---
[INFO] Copying D:\Hygieia-master\api\target\api.jar -> D:\Hygieia-master\api\target\docker\hygieia\api.jar
[INFO] Copying D:\Hygieia-master\api\docker\Dockerfile -> D:\Hygieia-master\api\target\docker\Dockerfile
[INFO] Copying D:\Hygieia-master\api\docker\properties-builder.sh -> D:\Hygieia-master\api\target\docker\properties-builder.sh
[INFO] Copying D:\Hygieia-master\api\docker\README.md -> D:\Hygieia-master\api\target\docker\README.md
[INFO] Building image hygieia-api
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.255 s
[INFO] Finished at: 2016-08-17T17:10:51+05:30
[INFO] Final Memory: 53M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project api: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException




```

**Comment by mattnworb** [comment]
The Maven snippet posted doesn't mention what the actual error is. Can you rerun your build with `-e` (like the Maven output mentions) and post the output?

**Comment by mattnworb** [comment]
> [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project api: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]


This likely either means that you do not have the docker daemon running at this address, or you need to set the DOCKER_HOST environment variable (as mentioned in the README) to the correct address for your docker installation.

**Comment by Farhood0011** [comment]
I am having this error while building the docker image 

[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.14:build (default) on project mavenSensor: Unable to parse configuration of mojo com.spotify:docker-maven-plugin:0.4.14:build for parameter targetpath: Cannot find 'targetpath' in class org.apache.maven.model.Resource -> [Help 1]

Can anyone help me ?

thanks

**Comment by stuartg23** [comment]
Farhood0011. Did you ever get an answer?

**Comment by Ademord** [comment]
I am also looking for an answer to @Farhood0011 's point..

**Comment by Biswa5945** [comment]
@Farhood0011 , @stuartg23  and @Ademord , you may try using Camel Case for the tag names like 'targetPath' instead of 'targetpath'. That should resolve the issues.

**Comment by rameshdhanapal** [comment]
set DOCKER_HOME in environment property 
example 
variable DOCKER_HOME
VALUE : tcp://localhost:2375

**Comment by stuartg23** [comment]
Thank you, I will try that.
