### ISSUE TITLE
Docker for Mac support

### ISSUE THREAD

**Issue by arey** [spotify/docker-maven-plugin#270]
## Description

I’m following the "Spring Boot with Docker" guide https://spring.io/guides/gs/spring-boot-docker/ while using "Docker for Mac" https://docs.docker.com/docker-for-mac/ instead of boot2docker
When I execute a ```mvn docker:build``, I’ve got an HttpHostConnectException.
I don’t know on which port is listening my Docker for Mac. 
Could you please update your readme.md ?

## How to reproduce

Install Docker for Mac then follow https://spring.io/guides/gs/spring-boot-docker/

* ```git clone https://github.com/spring-guides/gs-spring-boot-docker.git```
* ```cd gs-spring-boot-docker/final```
* ```mvn package docker:build ```

## What do you expect

Successfull maven build

## What happened instead

BUILD FAILURE

## Software:

- docker version: 1.12.1-beta24
- docker-maven-plugin version: 0.2.3
- maven version: 3.3.9

## Full backtrace

```text
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.3:build (default-cli) on project gs-spring-boot-docker: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
```

**Comment by mattnworb** [comment]
Hi @arey, that guide is using an old version of the plugin. Please try the latest version of the plugin (`0.4.11`) - it should support DFM transparently.

**Comment by arey** [comment]
It's working with the 0.4.11 plugin version. Thanks @mattnworb
