### ISSUE TITLE
Issue running Docket with Spring Boot.

### ISSUE THREAD

**Issue by harishkadamudi** [spotify/docker-maven-plugin#273]
## Description

Can't Run Docker with Spring Boot.

## How to reproduce

I am following one the example posted in Spring Guide. Link for reference link - https://spring.io/guides/gs/spring-boot-docker/
When i execute maven goal, package build:docket I am getting exception - Failed to execute goal com.spotify:docker-maven-plugin.

## What do you expect

Run Docker successfully as described in the post. 

## What happened instead

Exception Occured.

## Software:

- docker version: 1.12
- docker-maven-plugin version: 0.4.9
- maven version: 3.3.9	

## Full backtrace
Exception-
Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project sample-docker: Exception caught: open /var/lib/docker/aufs/layers/fc8d5f1f258fe1b19093667cde51918813aba8fe5dd68631b424dbda1b9eae56: no such file or directory -> [Help 1].
```text

```

**Comment by harishkadamudi** [comment]
I followed what is being answered [here ](https://stackoverflow.com/questions/30984569/error-error-creating-aufs-mount-to-when-building-dockerfile) but no luck. Could please help me on this. Thanks.

**Comment by mattnworb** [comment]
This sounds like an issue with your Docker installation itself and not with this Maven plugin that communicates with Docker. The linked Stackoverflow question seems to imply this as well. I would suggest uninstalling and reinstalling Docker on your system, and verifying that you can build Docker images normally with commands like `docker build .` and/or other Docker commands like `docker ps` or `docker images` before trying to use any Maven plugins that need a healthy docker instance to talk to.
