### ISSUE TITLE
com.spotify:docker-maven-plugin:0.4.9:build (default-cli) on project eureka-server: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

### ISSUE THREAD

**Issue by santhoshanna** [spotify/docker-maven-plugin#275]
## Description

[Add feature/bug description here]
## How to reproduce

[Add steps on how to reproduce this issue]
The Maven Plugin portion is :+1: 
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.9</version>
                <configuration>
                    <dockerHost>https://192.168.99.101:2376</dockerHost> 
                    <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <resources>
                        <resource>
                            
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                </configuration>
            </plugin>
When i run docker-machine ls i get below response:
C:\Users\cups>docker-machine ls
NAME           ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default        -        virtualbox   Running   tcp://192.168.99.101:2376           v1.11.1
proxy          -        virtualbox   Stopped                                       Unknown
proxymachine   -        virtualbox   Stopped                                       Unknown

I am using windows 7(64 bit).
C:\Users\cups>docker-machine --version
docker-machine version 0.7.0, build a650a40

C:\Users\cups>docker --version
Docker version 1.11.1, build 5604cbe

virtual box version is 5.1.6
## What do you expect

[Describe what do you expect to happen]
## What happened instead

[Describe the actual results]
## Software:
- docker version: Docker version 1.11.1, build 5604cbe
- docker-maven-plugin version: 0.4.9
- maven version: latest
## Full backtrace

com.spotify:docker-maven-plugin:0.4.9:build (default-cli) on project eureka-server: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

```
```

**Comment by mattnworb** [comment]
> PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

sounds like an issue with TLS certificates - are you setting the environment variables that docker-machine exports? see https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#https-support

**Comment by santhoshanna** [comment]
I did that, but it did not help:
C:\Users\cups>docker-machine env default
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\cups\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env default') DO @%i

C:\Users\cups>@FOR /f "tokens=*" %i IN ('docker-machine env default') DO @%i

Also i upgraded the docker version:
C:\Users\cups>docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

But these do not seem to help.

Also how do i use the api you mentioned??
I tried setting:
<dockerHost>https://boot2docker:2376</dockerHost> but i get unknowhost exception..

**Comment by santhoshanna** [comment]
Sorry, this is how my pom.xml looks:
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.4.13</version>
				<configuration>
				 	<dockerHost>https://boot2docker:2376</dockerHost> 
					
					<imageName>${docker.image.prefix}/${project.artifactId}</imageName>
					<dockerDirectory>src/main/docker</dockerDirectory>
					<resources>
						<resource>
							
							<directory>${project.build.directory}</directory>
							<include>${project.build.finalName}.jar</include>
						</resource>
					</resources>
				</configuration>
			</plugin>

**Comment by santhoshanna** [comment]
[pom.txt](https://github.com/spotify/docker-maven-plugin/files/471315/pom.txt)

Please find attached my pom.xml.. I am currently using latest version of spotify plugin 0.4.13

**Comment by vishwaraja** [comment]
I have the same issue too, though the context is set with the right environment variables for the plugin.

**Comment by davidxia** [comment]
Is this still an issue?

**Comment by davidxia** [comment]
Closing for now. Please comment here if the latest version doesn't work.
