### ISSUE TITLE
What are the plugin version requirements for docker versions?

### ISSUE THREAD

**Issue by itaied246** [spotify/docker-maven-plugin#276]
## Description

I can't figure out which version of the plugin will work with my docker service.  
It would be helpful to mention which version can work with each release.

## How to reproduce

I'm running the plugin on docker version 1.7 and it builds the image fine, but running on 1.10 causes unexpected exception.

## What do you expect

A docker image to be built

## What happened instead

Exception in the build phase

## Software:

- docker version: 1.10
- docker-maven-plugin version: 0.4.0
- maven version: 3.0.5

**Comment by mattnworb** [comment]
What are the errors you are getting on 1.10?

**Comment by mattnworb** [comment]
If I had to guess, I would speculate that the issues with 1.10 are related to https://github.com/spotify/docker-maven-plugin/issues/271#issuecomment-245276445.

I am going to close this issue on that theory but please re-open if the unexpected exception happens to have another cause.
