### ISSUE TITLE
Request error: GET http://112.124.50.158:5000/version: 404: HTTP 404 Not Found

### ISSUE THREAD

**Issue by catslave** [spotify/docker-maven-plugin#277]
## Description

```
mvn package docker:build
```

then throw that error.

My Docker Image Url: http://112.124.50.158:5000/v2

and My pom.xml:
```
                <configuration>
                    <dockerHost>http://112.124.50.158:5000</dockerHost>
                    <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
                </configuration>

**Comment by mattnworb** [comment]
`dockerHost` is meant to be the host of the *docker daemon* to use in building docker images - the use of port 5000 in your `dockerHost` value suggests to me that you are instead pointing at a docker registry instead.

**Comment by brightzheng100** [comment]
I believe it's because of DOCKER_HOST related issue.
I found that adding "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock" as part of DOCKER_OPTS in docker configuration file (e.g. /etc/default/docker in Ubuntu) is a very good practice. Have a try.

The use of port 5000 may be wrong as it's likely the private Docker Registry's port, not Docker daemon.

**Comment by mattnworb** [comment]
Closing this issue with the assumption that the above comments will fix the issue, but if you think they are incorrect and are still having issues please re-open it.
