### ISSUE TITLE
Support URL / Git Repo Build Context Declaration

### ISSUE THREAD

**Issue by midnightconman** [spotify/docker-maven-plugin#279]
## Description

Currently you can only specify a context directory using the `<dockerDirectory>` parameter. As of docker 1.12 build contexts can be url's or git repositories... can we extend this parameter to allow url build contexts or maybe create another parameter called `<buildContext>`? 

https://docs.docker.com/engine/reference/commandline/build/
## Software:
- docker version: 1.12
- docker-maven-plugin version: 0.4.13
- maven version: 3.3.9

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
