### ISSUE TITLE
Support for Maven like publishing into release and snapshot registry

### ISSUE THREAD

**Issue by christiangalsterer** [spotify/docker-maven-plugin#285]
Short version:
In short the plugin should support automatic deployment in either a release or snapshot registry based on the version/tag of the docker image applying the same rule as for Maven artefacts.

Long version:
In larger organizations with a lot of images it is common that more strict quality rules are applied combined with a high level of automation. 
E.g. one guidelines is to separate "SNAPSHOT" and release build into two different registries.
With the number of images growing manually changing the image name/URL for the registry is tedious and error prone. Therefore the plugin should apply this step automatically. E.g. Nexus 3 is an example for such a repo where you can define multiple registries bases on there version also for Docker images.

High level changes needed:
Allow to support two URL/ name prefixes to be specified. And based on the version/tag publish/deploy to either the snapshot or release repository. Optionally maybe allow to specify regular expression if not the Maven default versioning scheme is applied to allow to accommodate to different company standards.

**Comment by thiagolsfortunato** [comment]
+1
