### ISSUE TITLE
Should allow variable substitution on copied files

### ISSUE THREAD

**Issue by bgoldowsky** [spotify/docker-maven-plugin#288]
## Description

Files in the docker directory, or those copied in via <resources>, may need variable substitution.  This does not currently seem to be possible.

## How to reproduce

My configuration includes:

```
<plugin>
   <groupId>com.spotify</groupId>
   <artifactId>docker-maven-plugin</artifactId>
   <version>0.4.13</version>
   <configuration>
      <dockerDirectory>docker</dockerDirectory>
      <resources>
         <resource>
            <targetPath>/</targetPath>
            <directory>${project.build.directory}</directory>
            <include>${project.build.finalName}.war</include>
         </resource>
       ...

```
In the Dockerfile, I attempted to use:

`ADD ${project.build.finalName}.war   /usr/local/tomcat/webapps/ROOT.war
`
## What do you expect

Would like the ${project.build.finalName} to be replaced with the value of that variable.

## What happened instead

Variable is not replaced, and docker build fails.

## Software:

- docker version: 1.21.1, Docker for Mac
- docker-maven-plugin version: 0.4.13
- maven version: 3.3.9

**Comment by adriens** [comment]
You mean like Rocker (https://github.com/grammarly/rocker) does ?

**Comment by teriiehina** [comment]
I had the same problem and used [this tip](https://github.com/spotify/docker-maven-plugin/issues/25#issuecomment-88796978)

I then bind the `docker:build` goal to the `package` phase as [detailed here](https://github.com/spotify/docker-maven-plugin#bind-docker-commands-to-maven-phases).

Everything is working fine. I hope it applies to your need.

**Comment by kuboluch** [comment]
It would be a really nice feature.
I don't want to use xml plugin syntax instead of Dockerfile's, but I want to control base image version using maven properties. 
Would it be a problem, assuming that plugin does nothing more than copying files from dockerDirectory to buildDirectory/docker during build, if it could do resource filtering additionally?

**Comment by mattnworb** [comment]
I think this is covered in #25 - see the [comment](https://github.com/spotify/docker-maven-plugin/issues/25#issuecomment-88796978) that @teriiehina linked to
