### ISSUE TITLE
Multiple executions of plugin conflict due to hard-coded working directory

### ISSUE THREAD

**Issue by ankon** [spotify/docker-maven-plugin#293]
## Description

I'm using the plugin to produce Docker containers ... But in my project I'm building *multiple* containers, with multiple executions of the docker-maven-plugin. This doesn't work properly: the plugin uses ${project.build.directory}/docker as working directory, and doesn't clean up this directory after it is done.

## How to reproduce

~~~~
<plugin>
	<groupId>com.spotify</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>0.4.13</version>
	<executions>
		<execution>
			<id>build-1</id>
			<goals>
				<goal>build</goal>
			</goals>
			<configuration>
				<imageName>busybox</imageName>
				<dockerDirectory>${basedir}/src/docker/build-1</dockerDirectory>
				<resources>
					<resource>
						<targetPath>/</targetPath>
						<directory>${project.build.directory}/build-1</directory>
					</resource>
				</resources>
			</configuration>
		</execution>
		<execution>
			<id>build-2</id>
			<goals>
				<goal>build</goal>
			</goals>
			<configuration>
				<imageName>busybox</imageName>
				<dockerDirectory>${basedir}/src/docker/build-2</dockerDirectory>
				<resources>
					<resource>
						<targetPath>/</targetPath>
						<directory>${project.build.directory}/build-2</directory>
					</resource>
				</resources>
			</configuration>
		</execution>
	</executions>
</plugin>
~~~~

## What do you expect

Build context for `build-1` only contains contents from ${project.build.directory}/build-1, ditto for `build-2`.

## What happened instead

Build context for `build-1` is "correct", but the build context for build-2 contains everything from build-1 and build-2.

## Software:

- docker-maven-plugin version: 0.4.13

**Comment by ankon** [comment]
The problem is here: https://github.com/spotify/docker-maven-plugin/blob/v0.4.13/src/main/java/com/spotify/docker/BuildMojo.java#L379

Either the destination needs to be cleaned after the run, or a new one should be used for each run.

Cleaning might be "expensive" for regular users, so I'd propose to just make it possible for advanced users to configure the directory returned by `#getDestination()`.

**Comment by qiuwei** [comment]
+1 

I hope this can be merged to the master branch soon
