### ISSUE TITLE
Push Docker Image

### ISSUE THREAD

**Issue by ahmetkarakaya** [spotify/docker-maven-plugin#296]
## Description
Could not push the docker image to the docker.io repository
[Add feature/bug description here]

## How to reproduce
Each time I try to push image
[Add steps on how to reproduce this issue]

## What do you expect
I want to see the image name in the list, of https://hub.docker.com/r/ahmetkarakaya/repo1/ 
[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- docker version: 1.12.0
- docker-maven-plugin version: 0.4.11
- maven version: 3.2.3

## Full backtrace

[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ gs-spring-boot-docker ---
[INFO] Building jar: C:\Users\ttahkarakaya.TURKCELL\Desktop\gs-spring-boot-docker\complete\target\gs-spring-boot-docker-0.1.0.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.4.2.RELEASE:repackage (default) @ gs-spring-boot-docker ---
[INFO]
[INFO] --- docker-maven-plugin:0.4.11:build (default-cli) @ gs-spring-boot-docker ---
[INFO] Copying C:\Users\ttahkarakaya.TURKCELL\Desktop\gs-spring-boot-docker\complete\target\gs-spring-boot-docker-0.1.0.jar -> C:\Users\ttahkarakaya.TURKCELL\D
-docker\complete\target\docker\gs-spring-boot-docker-0.1.0.jar
[INFO] Copying src\main\docker\Dockerfile -> C:\Users\ttahkarakaya.TURKCELL\Desktop\gs-spring-boot-docker\complete\target\docker\Dockerfile
[INFO] Building image docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker
Step 1 : FROM frolvlad/alpine-oraclejdk8:slim
 ---> f8103909759b
Step 2 : VOLUME /tmp
 ---> Using cache
 ---> 36841e0d87cf
Step 3 : ADD gs-spring-boot-docker-0.1.0.jar app.jar
 ---> 6ef1582aca5e
Removing intermediate container 0bfc9fcc8f60
Step 4 : RUN sh -c 'touch /app.jar'
 ---> Running in 0793aea1556d
 ---> c4b8911cf071
Removing intermediate container 0793aea1556d
Step 5 : ENV JAVA_OPTS ""
 ---> Running in 1f0c5db71b84
 ---> f7d64cfaa34d
Removing intermediate container 1f0c5db71b84
Step 6 : ENTRYPOINT sh -c java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
 ---> Running in dd555e3e3b89
 ---> b71f4b224bbd
Removing intermediate container dd555e3e3b89
Successfully built b71f4b224bbd
[INFO] Built docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker
[INFO] Tagging docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker with 0.1.0
[INFO] Tagging docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker with latest
[INFO] Pushing docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker
The push refers to a repository [docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker]
db4ee565a05f: Preparing
1d63660fa197: Preparing
a27c88827076: Preparing
58f7b9930e4f: Preparing
9007f5987db3: Preparing
[WARNING] Failed to push docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker, retrying in 10 seconds (1/5).
[INFO] Pushing docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker
The push refers to a repository [docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker]
db4ee565a05f: Preparing
1d63660fa197: Preparing
a27c88827076: Preparing
58f7b9930e4f: Preparing
9007f5987db3: Preparing
[WARNING] Failed to push docker.io/ahmetkarakaya/repo1/gs-spring-boot-docker, retrying in 10 seconds (2/5).
Terminate batch job (Y/N)? y

C:\Users\ttahkarakaya.TURKCELL\Desktop\gs-spring-boot-docker\complete>

```text
[Paste full backtrace here]
```POM.XML

  <properties>
        <docker.image.prefix>docker.io/ahmetkarakaya/repo1</docker.image.prefix>
        <java.version>1.8</java.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <!-- tag::plugin[] -->
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.4.11</version>
                <configuration>
                    <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
					<serverId>docker-hub</serverId>
					<registryUrl>https://index.docker.io/v1/</registryUrl>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.jar</include>
                        </resource>
                    </resources>
					
					<imageTags>
					   <imageTag>${project.version}</imageTag>
					   <imageTag>latest</imageTag>
					</imageTags>					
                </configuration>
            </plugin>
            <!-- end::plugin[] -->
        </plugins>
    </build>

**Comment by mattnworb** [comment]
If you let the plugin finish before terminating, after a few retries it will output the underlying error message. 

It is likely an auth issue or something with docker daemon. Can you push using 'docker push' from the CLI?

**Comment by ahmetkarakaya** [comment]
[INFO] Final Memory: 29M/413M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (default-cli) on project gs-spring-boot-docker: Exception caught: unauthorized: authentication required
-> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by ahmetkarakaya** [comment]
Here is my server credentials, I am sure that password is correct, What am I missing to fill?
	 <server>
    <id>docker-hub</id>
    <username>ahmetkarakaya</username>
    <password>XXXXX</password>
    <configuration>
      <email>ahmet.krky@gmail.com</email>
    </configuration>
  </server>

**Comment by thm1118** [comment]
I have same issue.
it worked after use simple password without special character which needing to escape.

**Comment by iwannarun** [comment]
Hi,It worked after move  "setting.xml"  to ~/.m2/ ,then put your credentials in your Maven's global settings.xml.
