### ISSUE TITLE
pushImageTags should be pushImageTag for CLI tags in README#usage 

### ISSUE THREAD

**Issue by justinharringa** [spotify/docker-maven-plugin#304]
## Description

It appears that there is a typo in the doc for https://github.com/spotify/docker-maven-plugin#usage. The document correctly mentions that you can use pushImageTag and then in the last blurb about using the tags in the command-line the doc says to use pushImageTag**s**. 

## How to reproduce

Run ```mvn ... docker:build -DpushImageTags -DdockerImageTags=latest -DdockerImageTags=another-tag``` and note that it uses the default behavior for pushImageTag of false. 

## What do you expect

Should be running ```mvn ... docker:build -DpushImageTag -DdockerImageTags=latest -DdockerImageTags=another-tag```

## Simple bug (doc) fix

I've submitted #303 to fix the doc. I suppose another option would be to also support the plural version but I doubt that's necessary.

**Comment by justinharringa** [comment]
I also added a fix to the dockerImageTags parameter. It should be comma-delimited otherwise the Nth instance of dockerImageTags will be the tag that gets pushed and the rest will be ignored.

**Comment by davidxia** [comment]
fixed by #303
