### ISSUE TITLE
Google Container Registry - Failed to parse auth string for https://us.gcr.io

### ISSUE THREAD

**Issue by guzmo** [spotify/docker-maven-plugin#305]
## Description

I've added docker-maven-plugin to my spring-boot app and the image is being built, but when it tries to push to google container registry it says: **Failed to parse auth string for https://us.gcr.io**

Docker login command:
`docker login -e 1234@567.com -u _json_key -p "$(cat ~/.secrets/my-secret.json)" https://us.gcr.io`

When I run docker push .... locally it works fine and everything gets pushed.

Been trying to find other issues here about it but couldn't find any.

## Software:

- docker version:  1.12.6
- docker-maven-plugin version: 0.4.13
- maven version: 3.2.3
- OS: Windows 8

**Comment by mattnworb** [comment]
Sorry for the lack of a reply. I am fairly certain that this would be fixed in 0.4.14, but I know for sure it is fixed in #339.
