### ISSUE TITLE
Plugin hangs if project is not git repository 

### ISSUE THREAD

**Issue by niksajakovljevic** [spotify/docker-maven-plugin#313]
## Description

Running `mvn clean project docker:build` hangs forever if project is not Git repository.

## How to reproduce

Great a new project. Add maven POM file and some class file. Try building a docker image.
Should hang forever on this line
`[INFO] --- docker-maven-plugin:0.4.13:build (default-cli) @ xxxxxxxxx ---`

Now do `git init` in the same folder. Try building a docker image and it will succeed. 

## Software:

- docker version: 1.10.1, build 9e83765 (OS X 10.10.5 )
- docker-maven-plugin version: 0.4.13 ( but seems it affects previous versions as well)
- maven version: Apache Maven 3.3.3

**Comment by fmatar** [comment]
This issue needs to be closed, I can't reproduce it. Tried with maven 3.5.0, docker plugin 1.0.0 and it works

**Comment by mattnworb** [comment]
Thanks @fmatar for confirming.
