### ISSUE TITLE
Anyway to call Docker Squash Experimental Option

### ISSUE THREAD

**Issue by cwolfinger** [spotify/docker-maven-plugin#317]
Is there a way to call the Docker Squash experimental option ?  it is currently a query parameter passed into the build image command:

https://docs.docker.com/engine/api/v1.26/#operation/ImageBuild

**Comment by Deklin** [comment]
+1 on this, but more how about a generic way to pass additional CLI to docker as an overall solution.

**Comment by mattnworb** [comment]
@deklin the plugin communicates with docker via the Remote API and not the CLI, so there isn't any way to pass arbitrary flags or arguments as you would on the CLI.

**Comment by Deklin** [comment]
@mattnworb ah ! Thanks I wasn't aware of that.
