### ISSUE TITLE
Remove mandatory email from server settings

### ISSUE THREAD

**Issue by pierremorel-enactor** [spotify/docker-maven-plugin#318]
This is similar to https://github.com/spotify/docker-maven-plugin/issues/89

> We use [Config File Provider Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Config+File+Provider+Plugin) and [Credentials Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin) for managing the Maven settings.xml file in our build farm. Those plugins will stitch credentials into a settings.xml at the beginning of a build, but the XML stanzas they stitch into the settings.xml file look like this:

```
<server>
<id>server_id</id>
<username>...</username>
<password>...</password>
</server>
```

No `<configuration><email>...</email></configuration>` entries are created.

However, since the [issue](https://github.com/spotify/docker-maven-plugin/issues/89) was resolved, docker login no longer require the email address. See
https://github.com/docker/docker/pull/16183 (merged in docker 1.11)

Could we relaxed the email restriction as we are not currently able to use Jenkins + Credentials Plugin + Spotify Maven Plugin.

**Comment by vromero** [comment]
If compatibility will older versions is an issue, it could perhaps be possible  to set a default email in the plugin configuration.
