### ISSUE TITLE
Error Parsing Reference : Not a valid repository/tag

### ISSUE THREAD

**Issue by Srigowri** [spotify/docker-maven-plugin#324]
## Edit: I found the work around. I enclosed P A Vijaya within double quotes. It works fine

**## Description**

Error Parsing Reference **## :"A"** is not a valid repository/tag : repository name must be lowercase

**## How to reproduce**
docker run -it -v $HOME/tf_files:/tf_files  gcr.io/tensorflow/tensorflow:latest-devel

I am trying the example given in tensorflow for poets

## What I think is the issue

echo $HOME gives /c/Users/P A Vijaya
The reason might be that P A Vijaya has spaces,the error exists. Also,its in the upper case.
I am unable to figure out the workaround

**Comment by mattnworb** [comment]
sounds like an issue for tensorflow or the docker project itself, and not this docker-client library
