### ISSUE TITLE
Docker build --network option

### ISSUE THREAD

**Issue by wjans** [spotify/docker-maven-plugin#325]
As of docker v1.13 the docker build command has an option `--network`.  I need to use this option to build my docker images via Maven.  Is there any way to specify the network?  

If not, would it be interesting to create a PR for specifying this in the build mojo?

- docker version: v17.03
- docker-maven-plugin version: 0.4.13
- maven version: 3.2.3

**Comment by Deklin** [comment]
I would recommend a generic parameter to pass additional CLI arguments, multiple issues opened would be solved by this feature.
