### ISSUE TITLE
Option to update base image before building

### ISSUE THREAD

**Issue by bgoldowsky** [spotify/docker-maven-plugin#329]
## Description

It would be convenient to have the option of updating the base image before building, equivalent to the command line:
`docker build --pull`

This could be selected for example with -DpullImage .

**Comment by albuch** [comment]
There is an option `-DpullOnBuild=<true|false>.` which already does this.

> pullOnBuild (Default: false)
      Flag to attempt to pull base images even if older images exists locally.
      Sends the equivalent of `--pull=true` to Docker daemon when building the
      image.
      User property: pullOnBuild

You can check the full list of parameters with the help command:
`mvn com.spotify:docker-maven-plugin:<version>:help -Ddetail=true`
