### ISSUE TITLE
autoPull on image level (not global)

### ISSUE THREAD

**Issue by ocker-docker-gummi-klokker** [spotify/docker-maven-plugin#344]
## Description

autoPull is a global configuration that is not allowed per image. This is a problem if we have 
an integration test that first build an image and then pull another image. If autoPull is true, 
the test fails because it is not able to pull the locally build image. If autoPull is false, changes 
to a previously pulled image are not picked up i.e. at the first run the first image is build and 
the other image is pulled, but if we make changes to the pulled image (build and push a change 
on another build machine), these changes are not picked up on the following runs because we 
can't explicitly set autoPull to true on the dependent image.

Fix 1: Add a per image autoPull option (preferred solution)
Fix 2. If the global autoPull option is set to true, and any of the pulls fails, try to use locally build images.

## Software:

- docker version:  17.03.0-ce, build 60ccb22
- docker-maven-plugin version: 0.21.0
- maven version: 3.3.9

**Comment by davidxia** [comment]
@ocker-docker-gummi-klokker Thanks for the idea. Unfortunately, since this project is in bug-fix only mode, we probably won't be able to accommodate this feature. :(
