### ISSUE TITLE
when i run :mvn clean package I get this error  [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project vviton-service-product: Exception caught: ADD failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder982375770/vviton-service-product-bin.tar.gz: no such file or directory -> [Help 1]

### ISSUE THREAD

**Issue by lovechenrui** [spotify/docker-maven-plugin#347]
## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- docker version: [Add docker version here, client and server]
- docker-maven-plugin version: [Add docker-maven-plugin version here]
- maven version: [Add maven version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by lovechenrui** [comment]
Who can help me?

**Comment by mattnworb** [comment]
Does the file vviton-service-product-bin.tar.gz exist in the docker context directory?

**Comment by mattnworb** [comment]
Please provide all of the requested info in the issue template if you'd like assistance
