### ISSUE TITLE
Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project dj-atliwen-edi-eurekaserver: Exception caught: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Can not construct i nstance of com.spotify.docker.client.messages.RegistryAuth: no String-argument constructor/factory method to deserialize from String value ('wincred') [ERROR] at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.LinkedHashMap["credsStore"])

### ISSUE THREAD

**Issue by atliwen** [spotify/docker-maven-plugin#350]
## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- docker version: [Add docker version here, client and server]
- docker-maven-plugin version: [Add docker-maven-plugin version here]
- maven version: [Add maven version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by davidxia** [comment]
will be fixed by https://github.com/spotify/docker-client/pull/1023
