### ISSUE TITLE
The following plugins are not marked @threadSafe

### ISSUE THREAD

**Issue by sdandroid** [spotify/docker-maven-plugin#352]
mvn -T 8 build 

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in 
[WARNING] com.spotify:docker-maven-plugin:0.4.13
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************

**Comment by alexandrvb** [comment]
+1
