### ISSUE TITLE
Generated META-INF/maven/plugin.xml missing `imageName`

### ISSUE THREAD

**Issue by lanoxx** [spotify/docker-maven-plugin#353]
## Description

The maven plugin plugin generates a file under META-INF/maven/plugin.xml. This file does not contain the documentation for the `imageName` property. It seems that IntelliJ is parsing this file to identify the valid elements in for the plugin configuration thus imageName is highlighted red in my IDE.

## How to reproduce

Use IntelliJ IDE and add <imageName> under the <configuration> element.

## What do you expect

It should just work.

## What happened instead

Under <configuration> of the plugin `<imageName>` is highlighted red.

## Software:

- docker version: 1.17
- docker-maven-plugin version: 1.3.6
- maven version: 3.3.9

## Full backtrace
Not applicable.

**Comment by ingolfured** [comment]
I'm getting the same thing, any way to ignore this error? (maybe it's just Intellij problem?)

**Comment by davidxia** [comment]
Is this still an issue with the latest version?

**Comment by davidxia** [comment]
Closing for now. If it's still an issue, please provide steps to repro.
