### ISSUE TITLE
 Maven-Docker Build cannot create docker image 

### ISSUE THREAD

**Issue by uelker58** [spotify/docker-maven-plugin#357]
Hello, I have the following problem. When building a Docker image with dockerfile, I get the following error message. Docker plugin is used in maven. Strangely enough i can build a docker image in other spring boot applications and there i do not get such an error message. I use docker for windows. I would be pleased if I could help me.

[INFO] Building image portal-appJSF
Nov 20, 2017 6:18:37 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:2375: Connection reset by peer: socket write error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.721 s
[INFO] Finished at: 2017-11-20T18:18:37+01:00
[INFO] Final Memory: 30M/507M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project portal-appJSF: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException: Cannot retry request with a non-repeatable request entity: Connection reset by peer: socket write error -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by vladvesa** [comment]
I encounter the same problem. Did you find a solution?
Output of docker version:
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by mattnworb** [comment]
The error message in the original issue indicates that the docker daemon is not listening at the address the plugin is trying to communicate with it at. See the “Setup” section of the readme for how you can customize the address to reach docker at.

**Comment by vladvesa** [comment]
> echo %DOCKER_HOST%
tcp://localhost:2375

During the build i get this:
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.3.6:build (default) on project bcc-config-service-standalone: Execution default of goal com.spotify:dockerfile-maven-plugin:1.3.6:build failed: Illegal char <:> at index 3: tcp://localhost:2375 -> [Help 1]

**Comment by uelker58** [comment]
I solved the problem by using the new plugin dockerfile-maven. Was not the deamon as previously mentioned but the plugin.

**Comment by abhisheknn** [comment]
For me the issue was Capital letter in image name while building the Image .
For example following plugin configuration was giving me error .
 ```
<plugin>
            <groupId>com.spotify</groupId>
            <artifactId>dockerfile-maven-plugin</artifactId>
            <version>1.3.6</version>
            <configuration>
            <useConfigFile>false</useConfigFile>
            <useMavenSettingsForAuth>true</useMavenSettingsForAuth>	
                <repository>${docker.image.prefix}/dockerAgent</repository>
            <buildArgs>
		<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
			</buildArgs>
            </configuration>
	<executions>
	<execution>
		<id>default</id>
		<phase>install</phase>
		<goals>
			<goal>build</goal>
		</goals>
	</execution>
	</executions>
        </plugin> 
``` 

The Issue got resolved by changing the "dockerAgent" to dockeragent (all letters in small cases).

**Comment by oliviercwa** [comment]
I have the same issue running Docker and Maven on Windows. My configuration tag was 
                <configuration>
                    <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                     ...

And the ${project.artifactId} resolved to a name that had capital letters.
This led to the error "Cannot retry request with a non-repeatable request entity: Connection reset by peer: socket write error -> [Help 1]". 

Changing the docker image to lowercase fixed it.

Thanks abhisheknn

**Comment by rmoutray-configureone** [comment]
For me the issue was an extra `/` in the name. My configuration was `${docker.image.prefix}/${project.artifactId}`, and the prefix itself already had a `/`.

**Comment by ShreyasDeshpande** [comment]
> For me the issue was Capital letter in image name while building the Image .
> For example following plugin configuration was giving me error .
> 
> ```
> <plugin>
>            <groupId>com.spotify</groupId>
>            <artifactId>dockerfile-maven-plugin</artifactId>
>            <version>1.3.6</version>
>            <configuration>
>            <useConfigFile>false</useConfigFile>
>            <useMavenSettingsForAuth>true</useMavenSettingsForAuth>	
>                <repository>${docker.image.prefix}/dockerAgent</repository>
>            <buildArgs>
>    	<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
>    		</buildArgs>
>            </configuration>
>    <executions>
>    <execution>
>    	<id>default</id>
>    	<phase>install</phase>
>    	<goals>
>    		<goal>build</goal>
>    	</goals>
>    </execution>
>    </executions>
>        </plugin> 
> ```
> The Issue got resolved by changing the "dockerAgent" to dockeragent (all letters in small cases).

It worked for me as well.  Thanks a ton :)

**Comment by BhanuPrakash531** [comment]
> For me the issue was Capital letter in image name while building the Image .

Issue got resolved by changing the upper case to smaller case on the artifact id which is used for the docker image name. Thanks

**Comment by martinvw** [comment]
I believe this issue should re-opened, there is totally no error message that indicates a problem with uppercase / lowercase. This should be fixed in the plugin.

**Comment by Engaam** [comment]
> I had the same issue running Docker and Maven on Windows. My configuration tag was
> 
> ${docker.image.prefix}/${project.artifactId}
> ...
> 
> And the ${project.artifactId} resolved to a name that had capital letters.
> This led to the error "Cannot retry request with a non-repeatable request entity: Connection reset by peer: socket write error -> [Help 1]".
> 
> Changing the docker image to lowercase fixed it.
> 
> Thanks abhisheknn

This fixed it for me. seems to be an issue with the plugin

**Comment by DRoppelt** [comment]
I can confirm that changing the repository-name to my own value (instead of project.artifactId) fixed this. The `${project.groupId}/${project.artifactId}` has upper-case chars.
````
<plugin>
  <groupId>com.spotify</groupId
  <artifactId>dockerfile-maven-plugin</artifactId>
  <version>1.4.10</version>
...
  <configuration>
    <repository>${project.groupId}/${project.artifactId}</repository>
    <tag>${project.version}</tag>
  </configuration>
</plugin>
````
to 
````
<plugin>
  <groupId>com.spotify</groupId
  <artifactId>dockerfile-maven-plugin</artifactId>
  <version>1.4.10</version>
...
  <configuration>
    <repository>domain/my_project_name</repository>
    <tag>${project.version}</tag>
  </configuration>
</plugin>
````

**Comment by reddyraja86** [comment]
> > For me the issue was Capital letter in image name while building the Image .
> > For example following plugin configuration was giving me error .
> > ```
> > <plugin>
> >            <groupId>com.spotify</groupId>
> >            <artifactId>dockerfile-maven-plugin</artifactId>
> >            <version>1.3.6</version>
> >            <configuration>
> >            <useConfigFile>false</useConfigFile>
> >            <useMavenSettingsForAuth>true</useMavenSettingsForAuth>	
> >                <repository>${docker.image.prefix}/dockerAgent</repository>
> >            <buildArgs>
> >    	<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
> >    		</buildArgs>
> >            </configuration>
> >    <executions>
> >    <execution>
> >    	<id>default</id>
> >    	<phase>install</phase>
> >    	<goals>
> >    		<goal>build</goal>
> >    	</goals>
> >    </execution>
> >    </executions>
> >        </plugin> 
> > ```
> > 
> > 
> > The Issue got resolved by changing the "dockerAgent" to dockeragent (all letters in small cases).
> 
> It worked for me as well. Thanks a ton :)

> This solved the issue.Thanks.

**Comment by mohanr** [comment]
Don't understand why we don't think such issues are a serious thread to open-source in contemporary software.

**Comment by shreekrishna905** [comment]
Work for me. It is very simple issue. check name of your project.
I have name in Uppercase like this name = Xyz. I change to lower case and every thing work fine. ${project.name} = xyz . Thank you  all

**Comment by venkatnaveen7** [comment]
I too had the same problem
We need not remove the capital cases I belive

dockerfile plug in uses project version
my pom.xml was having  <version>0.0.1-SNAPSHOT</version> and i changed it to <version>0.0.1.SNAPSHOT</version>  and images built succesfully
