### ISSUE TITLE
OpenSource or not?

### ISSUE THREAD

**Issue by karlnicholas** [spotify/docker-maven-plugin#358]
## Description

18 pull requests ignored

## How to reproduce

check github

## What do you expect

pull requests addressed

## What happened instead

pull requests ignored

## Software:

- docker version: [Add docker version here, client and server]
- docker-maven-plugin version: [Add docker-maven-plugin version here]
- maven version: [Add maven version here]

## Full backtrace

```text
Pull request.
```

**Comment by mattnworb** [comment]
Hi @karlnicholas, as mentioned in the [README](https://github.com/spotify/docker-maven-plugin#the-future-of-docker-maven-plugin) and [CONTRIBUTING.md](https://github.com/spotify/docker-maven-plugin/blob/master/CONTRIBUTING.md), we don't plan on making major contributions to this repository going forward as we instead are using https://github.com/spotify/dockerfile-maven for many internal projects.

Spotify open sources code in the hopes that the work we have done is useful to others. In the lifetime of this repository we have about 20 contributors from outside Spotify and we've closed 135 issues. 

We are happy to accept pull requests and review issues when we can, but our time has to compete with other priorities and we also have to balance changes to the source code with how we use the code internally. The same is true of our other open source repositories related to Docker ([docker-client](https://github.com/spotify/docker-client), [dockerfile-maven](https://github.com/spotify/dockerfile-maven), [docker-gc](https://github.com/spotify/docker-gc), etc). 

If we are not able to review PRs as fast as contributors would like, or able to accept proposed changes or resolve issues in a way that the reporters would like, forking the code is always an option that we would have no problem with. Our goal with open sourcing code is to contribute back to the community, not to create or maintain the single "build docker images from Maven" plugin or to have a single project that solves every docker/maven need.

If there is a specific PR or issue you would like to have reviewed it would be more constructive to poke people in that PR or issue.

**Comment by karlnicholas** [comment]
I was looking for the EXPOSE option because OpenShift (Kubernetes?) needs to have a EXPOSE in the dockerfile for a service to be created when I create a new application from an image. Turns out that feature has been added. A documentation update would be useful. Thanks.

**Comment by karlnicholas** [comment]
@rhuss -- looks great thanks for heads-up.
