### ISSUE TITLE
[feature-request] Remove intermediate containers after build

### ISSUE THREAD

**Issue by dminca** [spotify/docker-maven-plugin#373]
## Preamble
After using this plugin on our buildmachines, we noticed after a period of time that our agents were failing to execute pipelines because disk was filling quite fast. The builds were not being able to cleanup after themselves with the help of this plugin because it didn't have this feature.

## Request details
During the `docker build` phase, we're requiring a mechanism to remove intermediate containers after a successful build. This option comes native in the `docker-engine`: `docker build --rm <other-params>`

As I saw by [browsing through the issues](https://github.com/spotify/dockerfile-maven/issues/4), the `docker build --no-cache` option already exists (which is awesome), imagine if you combine it with the `--rm` argument, then no one would actually be forced to setup cleanup crons on buildmachines for cleaning up containers/images.

```sh
# docker-build manpage: man docker-build
--rm=true|false
   Remove intermediate containers after a successful build. The default is true.
```

Please consider implementing this feature, as I don't think I'm the only one wanting to evade from these kind of errors, you're going to help many SysAdmins and Developers :sweat_smile: 

![screenshot from 2018-02-19 17-55-36](https://user-images.githubusercontent.com/5355219/36386482-8fd534d2-159e-11e8-8b3e-ba94a51a9efb.png)

**Comment by davidxia** [comment]
We recommend users switch to https://github.com/spotify/dockerfile-maven. This project is now bug fix only mode.
