### ISSUE TITLE
Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by Yamini-TWG** [spotify/docker-maven-plugin#374]
## Description
I am trying to run a Jenkins pipeline i make maven build, and using a spotify to convert artifact to docker image  and to push it to docker hub.

I am running build on kuberenetes pod with a docker dind/jdk/mvn/ image 

but its on failing with one constant error:
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
Mar 27, 2018 2:12:48 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80

[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.0:build (default) on project stocky-service: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 

when I am running on my local machine, I am not finding any issue, but when it comes to Jenkins pipeline its throwing error

**Comment by fatihdemirez** [comment]
I faced same issue  How to resolve it ?
