### ISSUE TITLE
happened an error when "mvn clean install docker:build"

### ISSUE THREAD

**Issue by planeo1105** [spotify/docker-maven-plugin#396]
## Description

[Add feature/bug description here]

[INFO] Building image chargerlink-monitor-web
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: Permission denied
Aug 15, 2018 6:49:06 AM com.spotify.docker.client.shaded.org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.999 s
[INFO] Finished at: 2018-08-15T06:49:06Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.1.1:build (default-cli) on project chargerlink-monitor-web: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: Permission denied -> [Help 1]

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

when I "mvn clean install docker:build" why I don't have Permission denied?

[Describe the actual results]

## Software:

- docker version: [Add docker version here, client and server]

17.06.2-ce

- docker-maven-plugin version: [Add docker-maven-plugin version here]

1.1.1

- maven version: [Add maven version here]

3.5.4

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by belloyang** [comment]
I came across the same issue. 
It's related with docker permission.  I assume you need to add sudo when you run docker directly. I have resolved this problem by giving non-root access to running docker. https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
