### ISSUE TITLE
skip docker build when packaging is pom

### ISSUE THREAD

**Issue by vineethkiv** [spotify/docker-maven-plugin#404]
## Description

The docker build is skipped when the project packaging is pom.
Change committed 3 years ago in 2015 in BuildMojo.java > weShouldSkipDockerBuild()
Release in may 2018. 
Any specific reason to do this?

## How to reproduce

Create maven project with packaging as pom and include docker maven plugin.

## What do you expect

Expect to build the project even when the packaging is pom.

## What happened instead

Skipped docker build for projects with pom packaging.

## Software:

- docker version: 18.06.1-ce
- docker-maven-plugin version: 1.1.0
- maven version: 3.3.9

## Full backtrace

```text

```

**Comment by mattnworb** [comment]
A project with packaging=pom does not produce any jar files. What do you want to be inside the docker image for the project?

**Comment by bguerin** [comment]
It can be POM packaging because nothing else is better ...
I wrap npm / bower build into a Maven one, to produce a zip file of an angular app.
This zip is transformed to a docker image
All of this into one maven project
What kind of packaging should I use ?

**Comment by vkiv2** [comment]
I have some projects to dockerize the nginx configurations too..

**Comment by vineethkiv** [comment]
I have some projects to dockerize the nginx configurations.

**Comment by awallat** [comment]
We have the same problem!
We have several multi-module projects where we have a "distribution"-module, which takes care of the docker image creation. Since this is a POM-project the image is not being build anymore with version 1.1.1.

Using Version 1.0.0 of the docker-maven-plugin still works!

So either remove this check or add an option that let's us disable this check.

**Comment by disrvptor** [comment]
Here's the commit in case anyone can get this team to accept a pull request
https://github.com/spotify/docker-maven-plugin/commit/ae2e50496ea00f0960f54bdbc6c800bfa4357456

**Comment by dcfsc** [comment]
We are building a Docker image in a submodule and with 1.2.0 it is now being skipped. There is no artifact to be stored in the Maven local repo, and there is no "none of the above" value in the Maven Packaging options, so `pom` is it. 

We could make a PR to check a setting before the build gets skipped, I suppose, but I am really curious what the use case for the original change was.

Perhaps the newer dockerfile-maven-plugin will not do this.

**Comment by bguerin** [comment]
We gave up on this plugin, and migrated to dockerfile one. This one does not block on POM packagings

**Comment by corentinarnaud** [comment]
This bug is still happening on 1.2.1.
I have a module that build and push an image on our repo.
There is no need to create a jar.

**Comment by smartsaif15** [comment]
This bug still exist ... unable to push image which can be created by child modules.
