### ISSUE TITLE
Plugin fails with osx

### ISSUE THREAD

**Issue by alonsoir** [spotify/docker-maven-plugin#412]
## Description

It is not working when i try to run mvn package docker:build. This is the  [code](https://github.com/alonsoir/stream-java8-test/tree/feature-add-docker).  

## How to reproduce

git clone https://github.com/alonsoir/stream-java8-test/tree/feature-add-docker
mvn package docker:build

## What do you expect

I expect the container with the image instantiated.

## What happened instead

https://pastebin.com/8QKieuHw

## Software:

- docker version: $ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

- docker-maven-plugin version: 1.2.0
- maven version: Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)

## Full backtrace

```text
https://pastebin.com/uXWiwZGE
```

**Comment by mattnworb** [comment]
The pom.xml you linked to is trying to build an image with name `aironman/MyStreamjava8`. Docker does not allow image names with upper-case characters.

The plugin does not handle the error response from the docker daemon well in this case, see https://github.com/spotify/docker-maven-plugin/issues/206
