### ISSUE TITLE
All 3 authentication mechanisms aren't working for 1.2.0 version

### ISSUE THREAD

**Issue by yemanasyan** [spotify/docker-maven-plugin#414]
I was using 1.2.0 version. Tried all 3 authentication mechanisms, all of them aren't working. The message was:
Exception caught: denied: requested access to the resource is denied -> [Help 1]

I've downgraded to 1.1.1 and it started working.

**Comment by SingletonPattern** [comment]
hi I have the same problem;but  I  also have this problem with  1.1.1
