### ISSUE TITLE
Custom dockerfile filename not working - v1.4.10

### ISSUE THREAD

**Issue by mattcopas** [spotify/docker-maven-plugin#415]
## Description

I'm trying to build a docker image using a Dockerfile called `Dockerfile-web" (Because I need 2 Dockerfiles in the same directory, hence the custom name)

Using `<dockerfile>Dockerfile-web</dockerfile>` does not work

## How to reproduce

Specify a Dockerfile that is not called Dockerfile using the `<dockerfile>` configuration option

## What do you expect

The plugin to use Dockerfile-web for building my docker image

## What happened instead

An error:
```
[INFO] --- dockerfile-maven-plugin:1.4.10:build (default-cli) @ client ---
[INFO] dockerfile: null
[INFO] contextDirectory: <my_proj_directory>
[INFO] Building Docker context <my_proj_directory>
[INFO] Path(dockerfile): null
[INFO] Path(contextDirectory): <my_proj_directory>
[ERROR] Missing Dockerfile in context directory <my_proj_directory>
```
Note the `[INFO] Path(dockerfile): null` (i'd expect this to be Dockerfile-web) and `Missing Dockerfile`
## Software:

- docker version: 
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
- docker-maven-plugin version: 1.4.10
- maven version: 3.5.2

## Full backtrace
See above

The relavant part of my pom:

```
<plugins>
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>web</id>
                        <!-- Do not bind these goals to a phase -->
                        <phase />
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                        <configuration>
                            <dockerfile>Dockerfile-web</dockerfile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
```

Error occurs using `mvn dockerfile:build`

The use of <dockerfile> is based on [this pr](https://github.com/spotify/dockerfile-maven/pull/89) which was released as of 1.4.10 (my version)

Please help :)

**Comment by Tool1990** [comment]
@mattcopas did you find a fix?

**Comment by Jayanta-Pal** [comment]
I changed the "spotify"  version to <version>1.4.13</version>
And then able to create build using "mvn package" from IDE(Eclipse) .
