### ISSUE TITLE
how to set the map in this property？

### ISSUE THREAD

**Issue by meme-lau** [spotify/docker-maven-plugin#423]
https://github.com/spotify/docker-maven-plugin/blob/dc265af355ac8e561b4f7b0eef35af52591c99da/src/main/java/com/spotify/docker/BuildMojo.java#L247

**Comment by mattnworb** [comment]
https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Mapping_Maps

**Comment by meme-lau** [comment]
😳😳😳Oops, i mean i will use ${dockerEnv} in pom <properties> to declare the docker env, but i don't know how to define a Map property

![1559492949657](https://user-images.githubusercontent.com/10671821/58764210-00b61680-8597-11e9-8b5b-3df4adcc857a.jpg)
