### ISSUE TITLE
推送镜像至私服时，即使设置的imageTag，仍然会生成一个latest的tag，且两个tag的镜像id相同，如何设置才能覆盖latest的tag而只生成自己设置的tag呢

### ISSUE THREAD

**Issue by xiaofengczy** [spotify/docker-maven-plugin#432]
## Description
推送镜像至私服时，即使设置的imageTag，仍然会生成一个latest的tag，且两个tag的镜像id相同，如何设置才能覆盖latest的tag而只生成自己设置的tag呢

设置:
![image](https://user-images.githubusercontent.com/31238142/65004455-090c4480-d92f-11e9-8383-1bed00ee1061.png)

执行结果:
![image](https://user-images.githubusercontent.com/31238142/65004539-4ec90d00-d92f-11e9-8b20-874a872c6fa1.png)

生成镜像结果 
![image](https://user-images.githubusercontent.com/31238142/65004559-60aab000-d92f-11e9-92e8-b0a160991259.png)

**Comment by liudc001** [comment]
you can do like this
<imageName>imageName:${project.version}</imageName>

**Comment by liudc001** [comment]
do not use imageTags,
you can do like this
`
    <imageName>imageName:${project.version}</imageName>
`

**Comment by xiaofengczy** [comment]
> <imageName>imageName:${project.version}</imageName>

thank you
