### ISSUE TITLE
Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project

### ISSUE THREAD

**Issue by kitkatlc** [spotify/docker-maven-plugin#449]
When I execute this command line: mvn clean package docker:build. 
I will get the error info:Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project test: Execution default-cli of goal com.spotify:docker-maven-plugin:1.0.0:build failed: A required class was missing while executing com.spotify:docker-maven-plugin:1.0.0:build: org/apache/commons/logging/LogFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.spotify:docker-maven-plugin:1.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/MavenRepository/com/spotify/docker-maven-plugin/1.0.0/docker-maven-plugin-1.0.0.jar
[ERROR] urls[1] = file:/D:/MavenRepository/com/spotify/docker-client/8.7.1/docker-client-8.7.1-shaded.jar
[ERROR] urls[2] = file:/D:/MavenRepository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[3] = file:/D:/MavenRepository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.8.8/jackson-jaxrs-json-provider-2.8.8.jar
[ERROR] urls[4] = file:/D:/MavenRepository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.8.8/jackson-jaxrs-base-2.8.8.jar
[ERROR] urls[5] = file:/D:/MavenRepository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.8/jackson-module-jaxb-annotations-2.8.8.jar
[ERROR] urls[6] = file:/D:/MavenRepository/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.8.8/jackson-datatype-guava-2.8.8.jar
[ERROR] urls[7] = file:/D:/MavenRepository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar
[ERROR] urls[8] = file:/D:/MavenRepository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
[ERROR] urls[9] = file:/D:/MavenRepository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar
[ERROR] urls[10] = file:/D:/MavenRepository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[11] = file:/D:/MavenRepository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
[ERROR] urls[12] = file:/D:/MavenRepository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
[ERROR] urls[13] = file:/D:/MavenRepository/org/glassfish/hk2/hk2-api/2.4.0-b34/hk2-api-2.4.0-b34.jar
[ERROR] urls[14] = file:/D:/MavenRepository/org/glassfish/hk2/hk2-utils/2.4.0-b34/hk2-utils-2.4.0-b34.jar
[ERROR] urls[15] = file:/D:/MavenRepository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b34/aopalliance-repackaged-2.4.0-b34.jar
[ERROR] urls[16] = file:/D:/MavenRepository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
[ERROR] urls[17] = file:/D:/MavenRepository/org/glassfish/hk2/hk2-locator/2.4.0-b34/hk2-locator-2.4.0-b34.jar
[ERROR] urls[18] = file:/D:/MavenRepository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
[ERROR] urls[19] = file:/D:/MavenRepository/org/glassfish/jersey/connectors/jersey-apache-connector/2.22.2/jersey-apache-connector-2.22.2.jar
[ERROR] urls[20] = file:/D:/MavenRepository/org/glassfish/jersey/media/jersey-media-json-jackson/2.22.2/jersey-media-json-jackson-2.22.2.jar
[ERROR] urls[21] = file:/D:/MavenRepository/org/glassfish/jersey/ext/jersey-entity-filtering/2.22.2/jersey-entity-filtering-2.22.2.jar
[ERROR] urls[22] = file:/D:/MavenRepository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[23] = file:/D:/MavenRepository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[24] = file:/D:/MavenRepository/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.jar
[ERROR] urls[25] = file:/D:/MavenRepository/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar
[ERROR] urls[26] = file:/D:/MavenRepository/com/github/jnr/jnr-unixsocket/0.8/jnr-unixsocket-0.8.jar
[ERROR] urls[27] = file:/D:/MavenRepository/com/github/jnr/jnr-ffi/2.0.3/jnr-ffi-2.0.3.jar
[ERROR] urls[28] = file:/D:/MavenRepository/com/github/jnr/jffi/1.2.9/jffi-1.2.9.jar
[ERROR] urls[29] = file:/D:/MavenRepository/com/github/jnr/jffi/1.2.9/jffi-1.2.9-native.jar
[ERROR] urls[30] = file:/D:/MavenRepository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
[ERROR] urls[31] = file:/D:/MavenRepository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar
[ERROR] urls[32] = file:/D:/MavenRepository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
[ERROR] urls[33] = file:/D:/MavenRepository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar
[ERROR] urls[34] = file:/D:/MavenRepository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar
[ERROR] urls[35] = file:/D:/MavenRepository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar
[ERROR] urls[36] = file:/D:/MavenRepository/com/github/jnr/jnr-constants/0.8.7/jnr-constants-0.8.7.jar
[ERROR] urls[37] = file:/D:/MavenRepository/com/github/jnr/jnr-enxio/0.9/jnr-enxio-0.9.jar
[ERROR] urls[38] = file:/D:/MavenRepository/com/github/jnr/jnr-posix/3.0.12/jnr-posix-3.0.12.jar
[ERROR] urls[39] = file:/D:/MavenRepository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[40] = file:/D:/MavenRepository/org/bouncycastle/bcpkix-jdk15on/1.52/bcpkix-jdk15on-1.52.jar
[ERROR] urls[41] = file:/D:/MavenRepository/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar
[ERROR] urls[42] = file:/D:/MavenRepository/ch/qos/logback/logback-classic/1.2.1/logback-classic-1.2.1.jar
[ERROR] urls[43] = file:/D:/MavenRepository/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar
[ERROR] urls[44] = file:/D:/MavenRepository/com/google/auth/google-auth-library-oauth2-http/0.6.0/google-auth-library-oauth2-http-0.6.0.jar
[ERROR] urls[45] = file:/D:/MavenRepository/com/google/auth/google-auth-library-credentials/0.6.0/google-auth-library-credentials-0.6.0.jar
[ERROR] urls[46] = file:/D:/MavenRepository/com/google/http-client/google-http-client/1.19.0/google-http-client-1.19.0.jar
[ERROR] urls[47] = file:/D:/MavenRepository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[48] = file:/D:/MavenRepository/com/google/http-client/google-http-client-jackson2/1.19.0/google-http-client-jackson2-1.19.0.jar
[ERROR] urls[49] = file:/D:/MavenRepository/com/typesafe/config/1.2.0/config-1.2.0.jar
[ERROR] urls[50] = file:/D:/MavenRepository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[51] = file:/D:/MavenRepository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[52] = file:/D:/MavenRepository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[53] = file:/D:/MavenRepository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[54] = file:/D:/MavenRepository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[55] = file:/D:/MavenRepository/org/sonatype/sisu/sisu-guice/3.2.5/sisu-guice-3.2.5-no_aop.jar
[ERROR] urls[56] = file:/D:/MavenRepository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[57] = file:/D:/MavenRepository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[58] = file:/D:/MavenRepository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[59] = file:/D:/MavenRepository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[60] = file:/D:/MavenRepository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[61] = file:/D:/MavenRepository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[62] = file:/D:/MavenRepository/org/eclipse/jgit/org.eclipse.jgit/3.2.0.201312181205-r/org.eclipse.jgit-3.2.0.201312181205-r.jar
[ERROR] urls[63] = file:/D:/MavenRepository/com/jcraft/jsch/0.1.46/jsch-0.1.46.jar
[ERROR] urls[64] = file:/D:/MavenRepository/com/googlecode/javaewah/JavaEWAH/0.5.6/JavaEWAH-0.5.6.jar
[ERROR] urls[65] = file:/D:/MavenRepository/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar
[ERROR] urls[66] = file:/D:/MavenRepository/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar
[ERROR] urls[67] = file:/D:/MavenRepository/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.apache.commons.logging.LogFactory
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException.

**Comment by chandinikhetawat** [comment]
@kitkatlc  I am facing the same issue. Since you have closed this issue I am assuming it got resolved. How did you resolve it?

**Comment by kitkatlc** [comment]
I try to unload the maven and reload it. It can execute the plugin only one time. so I close the issue,But after that it can not execute the plugin successfully.As far as i known the plugin has the issue on the win10 operating system.

**Comment by chandinikhetawat** [comment]
Thanks for response @kitkatlc . For me it works on local machine (mac) but fails on jenkins
