### ISSUE TITLE
Remove image before building

### ISSUE THREAD

**Issue by jorgemoralespou** [spotify/docker-maven-plugin#47]
If this plugin is integrated into a CI server or even a developer's machine, after quite some builds you end up with a lot of dangling images (with name <none>). This can be avoided by deleting the image just before building, with a call to DockerClient.removeImage

**Comment by rohansingh** [comment]
Since the accrual of images over time is a problem that spans several tools, we've chosen to have a standalone solution: https://github.com/spotify/docker-gc

If you cron docker-gc on your CI server, it should take care of the problem. Is that an acceptable solution for your use case?

**Comment by jorgemoralespou** [comment]
It can be a solution for a CI server, but not so much for a developer box, as developers sometimes uses windows (yes, incredible, but they do) and I think that the plugin could have a clean goal in order to remove the old image before building the new one, or after the new one is built.
And of course, your tool assume anyone uses a debian based box, but the logic behind it is easy to implement in any other distro. The problem is developers sometimes doesn't know enough, and they end up polluting their local registry easily.

**Comment by rohansingh** [comment]
@rculbertson What do you think about this?

**Comment by rculbertson** [comment]
I think it would be fine to add a remove goal which exposes the DockerClient.removeImage functionality. You could then have two executions of the plugin, one to delete the old image, and another to build the new one. That would only work if your old and new images have the same name though.

**Comment by rohansingh** [comment]
Cool. @jorgemoralespou, if you're interested in implementing this I think we'd be open to a pull request.

**Comment by krystiannowak** [comment]
@rohansingh please check this #62 pull request adding removeImage mojo, which removes the image (or tag in fact, too) with -f option on (but without pruning parents)
