### ISSUE TITLE
SNAPSHOT build

### ISSUE THREAD

**Issue by filosganga** [spotify/docker-maven-plugin#53]
Hi,
You did great job with this plugin. Wondering if the SNAPSHOT version is available somewhere, because I need a feature been added on master but not yet released.

Cheers.

**Comment by davidxia** [comment]
@filosganga I can release one now.

**Comment by davidxia** [comment]
Released as 0.1.2. It should be available soon.

**Comment by filosganga** [comment]
Awesome, thanks!
