### ISSUE TITLE
Docker tag with force option

### ISSUE THREAD

**Issue by poznachowski** [spotify/docker-maven-plugin#70]
Hi, I'd like to make 'latest' tag in addition to each released version of my docker image. I could do that by using build goal with <imageTags> configuration. However, there is no way to enable force option for tagging.
My current workaround is to have 3 separate executions (all binded to package phase): build, remove latest tag image, and tag builded image with latest.

**Comment by poznachowski** [comment]
I managed to get force option enabled using latest docker client:
https://github.com/poznachowski/docker-maven-plugin/commit/ac7f54f49c93d94895931611af6e549e2f4dafb1

**Comment by davidxia** [comment]
oh awesome, want to open a PR for this?

**Comment by poznachowski** [comment]
Sure, I will.
However, I have a question, probably not related to the plugin itself:
After I did the change, I installed the plugin in my private Nexus repo with some custom version (manually, via Nexus upload artifact). When running against my version, the plugin does not download docker-client 2.7.20 automatically and throws ClassNotFoundException on DockerClient.
Do you know, what can be the cause of that?

I did add:
```
        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>docker-client</artifactId>
            <version>2.7.20</version>
        </dependency>
        <dependency>
            <groupId>com.spotify</groupId>
            <artifactId>docker-client</artifactId>
            <version>2.7.20</version>
            <classifier>shaded</classifier>
        </dependency>
```
as stated in: https://github.com/spotify/docker-client#maven

**Comment by poznachowski** [comment]
Ok, silly question that was. When I upload artifact via Nexus GAV params, it creates empty pom file..

**Comment by davidxia** [comment]
@poznachowski Can I close this?
