### ISSUE TITLE
add configuration to not fail if dockerFile absent

### ISSUE THREAD

**Issue by paskos** [spotify/docker-maven-plugin#77]
our project is gradually rolling docker container build and release.
We do it one project at a time. I tried to add plugin declaration (actual plugin, not plugin management) to all projects and expected docker build to only trigger for the projects actually having a dockerFile.
But the plugin fails when docker file is absent.
It would be nice if we could configure something like dockerFailIfDockerFileAbsent=false (default value would be true).

**Comment by davidxia** [comment]
@paskos Do you have a way to repro and a stacktrace?

**Comment by mattnworb** [comment]
Hi @paskos , I think the [property `<skipDockerBuild>true</skipDockerBuild>`](https://github.com/spotify/docker-maven-plugin/blob/cbac254bcaa1c1dcf9a638575ca6a14d5a4c953f/src/main/java/com/spotify/docker/BuildMojo.java#L102) would achieve the same result for you.

This is something we've done internally for multi-module Maven projects where the docker-maven-plugin configuration is applied globally (from `<pluginManagement>` or a parent POM) where only one or some of the modules should have a Docker image built.

**Comment by paskos** [comment]
It's not an issue anymore because we switch from dockerFile to docker properties in the plugin.
