### ISSUE TITLE
Builds fail on docker 1.4.1

### ISSUE THREAD

**Issue by NightWhistler** [spotify/docker-maven-plugin#79]
When building with docker 1.4.1, we get the following error:

```[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.6:build (default-cli) on project testproject: Exception caught: Request error: POST unix://localhost:80/v1.12/build?t=DPIT: 500: HTTP 500 Internal Server Error -> [Help 1]```

This seems related to (but not the same as) https://github.com/spotify/docker-client/issues/43

**Comment by davidxia** [comment]
@NightWhistler How are you running docker? What do the docker logs say?

**Comment by NightWhistler** [comment]
Turns out the problem was between keyboard and chair :)

For anybody else running into this problem: we had

``<imageName>DPIT</imageName>``

but image names have to be fully lower-case.

Changing it to

``<imageName>dpit</imageName>``

fixed the problem.

**Comment by yehuda54** [comment]
@NightWhistler THX SO MUCH!!!  After hours of reading about exporting DOCKER_HOST .. the issue was the stupid camel case for my image name.  I replaced the camel case with lowercase and dashes and it worked!!

Is this mentioned anywhere in the documentation??

**Comment by rhuss** [comment]
It's a general restriction of Docker, buried deep down in the Docker documentation.

**Comment by SSSoo** [comment]
@NightWhistler Thanks!!!

**Comment by deevodavis71** [comment]
Saved me a whole heap of trouble - thanks!!
