### ISSUE TITLE
How to push to privately hosted registry?

### ISSUE THREAD

**Issue by malnick** [spotify/docker-maven-plugin#92]
Hi there,

I'm trying to publish a built image to my privately hosted registry. However, this needs to be associated in the tag for the image as ```docker.mysite.com:5000/my_service-$version```.

The plugin associates <imageName>${docker.image.prefix}/${project.artifactId}-${project.version}</imageName> with the tag even if <registryUrl> tag is set to my privately hosted registry. 

This prevents me from pushing the image to that registry. I attempted to update <imageName> with the URL of my private registry, but failed as it tried to push it to a 192.168 IP address. 

My guess is that this plugin can auth to a private registry in the docker cloud registry, but it doesn't appear to support pushing to a privately hosted docker registry. Is that correct?

**Comment by g17** [comment]
I have the same problem. It tries to push to the docker host instead of to the docker registry.

My image is tagged properly according to https://docs.docker.com/reference/commandline/cli/#tag with the following pattern: *private.registry.example.com:user/name:version*

While pushing this plugin tries to do the following which is wrong:
*POST https://docker.host:2376/images/private.registry.example.com:user/name/push?tag=version*

**Comment by usopan** [comment]
Admins I am also facing the same issue with the maven plugin.

**Comment by usopan** [comment]
Solution here : https://github.com/spotify/docker-maven-plugin/pull/60/files#diff-bf77480d348d33f7011ad5fb4dabba51R50

**Comment by davidxia** [comment]
@malnick @usopan Sorry for the delay. docker-maven-plugin does support pushing to privately hosted registries in addition to docker hub. See https://github.com/spotify/docker-maven-plugin#authenticating-with-private-registries.

To tag your image to be pushed to a custom registry, do this in `pom.xml`:

```
<plugin>
        <groupId>com.spotify</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <configuration>
          <imageName> docker.mysite.com:5000/${project.artifactId}:${project.version}</imageName>
          ...
```

Does this solve your issue? If so, you can close this.

**Comment by usopan** [comment]
My issue is resolved. I cant close the issue

**Comment by amracel** [comment]
I tried this solution. But the plugin only seems to be able to use http:

INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://vaeb2-docregt.me:5000: Connection reset

How do I force it to use https:?
