### ISSUE TITLE
Add option to pull when building

### ISSUE THREAD

**Issue by phjardas** [spotify/docker-maven-plugin#95]
analogous to the `--pull` option of the docker command line interface.

**Comment by davidxia** [comment]
@phjardas What's your use case? I couldn't find the docs for the `--pull`. Do you have a link?

**Comment by phjardas** [comment]
We have Jenkins builds distributed over several slave servers. When one of our base images (tagged with `:latest` is updated in a job on one of the slaves, then other jobs that build on other slaves that use this base image should use the updated image.

Hence we want to always pull before we build.

Here's a link to the documentation: https://docs.docker.com/reference/commandline/build/

The option is `--pull=false   Always attempt to pull a newer version of the image`

Cheers!

**Comment by davidxia** [comment]
@phjardas It depends on a change to its dependency docker-client. But I can't get this test to pass https://github.com/spotify/docker-client/pull/217/files#r36091657

**Comment by phjardas** [comment]
Hooray, thanks a lot!
